// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetSpotSubAccountDetailTradeAccounts implements Serializable {
    /**
     * Currency
     */
    currency?: string;

    /**
     * Total funds in an account.
     */
    balance?: string;

    /**
     * Funds available to withdraw or trade.
     */
    available?: string;

    /**
     * Funds on hold (not available for use).
     */
    holds?: string;

    /**
     * Calculated on this currency.
     */
    baseCurrency?: string;

    /**
     * The base currency price.
     */
    baseCurrencyPrice?: string;

    /**
     * The base currency amount.
     */
    baseAmount?: string;

    /**
     *
     */
    tag?: string;

    private constructor() {}
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetSpotSubAccountDetailTradeAccounts {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetSpotSubAccountDetailTradeAccounts {
        return plainToClassFromExist(new GetSpotSubAccountDetailTradeAccounts(), jsonObject);
    }
}
