// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { GetSpotSubAccountsSummaryV2Items } from './model_get_spot_sub_accounts_summary_v2_items';
import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetSpotSubAccountsSummaryV2Resp implements Response<RestResponse> {
    /**
     * Current request page
     */
    currentPage: number;

    /**
     * Number of results per request. Minimum is 1, maximum is 100
     */
    pageSize: number;

    /**
     * Total number of messages
     */
    totalNum: number;

    /**
     * Total number of page
     */
    totalPage: number;

    /**
     *
     */
    @Type(() => GetSpotSubAccountsSummaryV2Items)
    items: Array<GetSpotSubAccountsSummaryV2Items>;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.currentPage = null;
        // @ts-ignore
        this.pageSize = null;
        // @ts-ignore
        this.totalNum = null;
        // @ts-ignore
        this.totalPage = null;
        // @ts-ignore
        this.items = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetSpotSubAccountsSummaryV2Resp {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetSpotSubAccountsSummaryV2Resp {
        return plainToClassFromExist(new GetSpotSubAccountsSummaryV2Resp(), jsonObject);
    }
}
