// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetFuturesSubAccountListV2Summary implements Serializable {
    /**
     * Total Account Equity
     */
    accountEquityTotal: number;

    /**
     * Total unrealisedPNL
     */
    unrealisedPNLTotal: number;

    /**
     * Total Margin Balance
     */
    marginBalanceTotal: number;

    /**
     * Total Position margin
     */
    positionMarginTotal: number;

    /**
     *
     */
    orderMarginTotal: number;

    /**
     * Total frozen funds for withdrawal and out-transfer
     */
    frozenFundsTotal: number;

    /**
     * total available balance
     */
    availableBalanceTotal: number;

    /**
     *
     */
    currency: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.accountEquityTotal = null;
        // @ts-ignore
        this.unrealisedPNLTotal = null;
        // @ts-ignore
        this.marginBalanceTotal = null;
        // @ts-ignore
        this.positionMarginTotal = null;
        // @ts-ignore
        this.orderMarginTotal = null;
        // @ts-ignore
        this.frozenFundsTotal = null;
        // @ts-ignore
        this.availableBalanceTotal = null;
        // @ts-ignore
        this.currency = null;
    }
    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetFuturesSubAccountListV2Summary {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetFuturesSubAccountListV2Summary {
        return plainToClassFromExist(new GetFuturesSubAccountListV2Summary(), jsonObject);
    }
}
