// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class AddSubAccountMarginPermissionResp
    implements Response<AddSubAccountMarginPermissionResp, RestResponse>
{
    /**
     *
     */
    data?: string;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): AddSubAccountMarginPermissionResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(AddSubAccountMarginPermissionResp, { data: jsonObject });
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }

    fromObject(jsonObject: Object): AddSubAccountMarginPermissionResp {
        return plainToInstance(AddSubAccountMarginPermissionResp, { data: jsonObject });
    }
}
