// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetFuturesSubAccountListV2Req implements Serializable {
    /**
     * Currecny, Default XBT
     */
    currency?: string = 'XBT';

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetFuturesSubAccountListV2Req` class.
     * The builder pattern allows step-by-step construction of a `GetFuturesSubAccountListV2Req` object.
     */
    static builder(): GetFuturesSubAccountListV2ReqBuilder {
        return new GetFuturesSubAccountListV2ReqBuilder(new GetFuturesSubAccountListV2Req());
    }

    /**
     * Creates a new instance of the `GetFuturesSubAccountListV2Req` class with the given data.
     */
    static create(data: {
        /**
         * Currecny, Default XBT
         */
        currency?: string;
    }): GetFuturesSubAccountListV2Req {
        let obj = new GetFuturesSubAccountListV2Req();
        if (data.currency) {
            obj.currency = data.currency;
        } else {
            obj.currency = 'XBT';
        }
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetFuturesSubAccountListV2Req {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetFuturesSubAccountListV2Req {
        return plainToClassFromExist(new GetFuturesSubAccountListV2Req(), jsonObject);
    }
}

export class GetFuturesSubAccountListV2ReqBuilder {
    constructor(readonly obj: GetFuturesSubAccountListV2Req) {
        this.obj = obj;
    }
    /**
     * Currecny, Default XBT
     */
    setCurrency(value: string): GetFuturesSubAccountListV2ReqBuilder {
        this.obj.currency = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetFuturesSubAccountListV2Req {
        return this.obj;
    }
}
