// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetSpotSubAccountListV2Req implements Serializable {
    /**
     * Current request page. Default is 1
     */
    currentPage?: number = 1;

    /**
     * Number of results per request. Minimum is 10, maximum is 100, default is 10.
     */
    pageSize?: number = 10;

    private constructor() {}
    /**
     * Creates a new instance of the `GetSpotSubAccountListV2Req` class.
     * The builder pattern allows step-by-step construction of a `GetSpotSubAccountListV2Req` object.
     */
    static builder(): GetSpotSubAccountListV2ReqBuilder {
        return new GetSpotSubAccountListV2ReqBuilder(new GetSpotSubAccountListV2Req());
    }

    /**
     * Creates a new instance of the `GetSpotSubAccountListV2Req` class with the given data.
     */
    static create(data: {
        /**
         * Current request page. Default is 1
         */
        currentPage?: number;
        /**
         * Number of results per request. Minimum is 10, maximum is 100, default is 10.
         */
        pageSize?: number;
    }): GetSpotSubAccountListV2Req {
        let obj = new GetSpotSubAccountListV2Req();
        if (data.currentPage) {
            obj.currentPage = data.currentPage;
        } else {
            obj.currentPage = 1;
        }
        if (data.pageSize) {
            obj.pageSize = data.pageSize;
        } else {
            obj.pageSize = 10;
        }
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetSpotSubAccountListV2Req {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetSpotSubAccountListV2Req {
        return plainToClassFromExist(new GetSpotSubAccountListV2Req(), jsonObject);
    }
}

export class GetSpotSubAccountListV2ReqBuilder {
    constructor(readonly obj: GetSpotSubAccountListV2Req) {
        this.obj = obj;
    }
    /**
     * Current request page. Default is 1
     */
    setCurrentPage(value: number): GetSpotSubAccountListV2ReqBuilder {
        this.obj.currentPage = value;
        return this;
    }

    /**
     * Number of results per request. Minimum is 10, maximum is 100, default is 10.
     */
    setPageSize(value: number): GetSpotSubAccountListV2ReqBuilder {
        this.obj.pageSize = value;
        return this;
    }

    build(): GetSpotSubAccountListV2Req {
        return this.obj;
    }
}
