// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class AddSubAccountMarginPermissionReq implements Serializable {
    /**
     * Sub account UID
     */
    uid: string;

    private constructor() {
        // @ts-ignore
        this.uid = null;
    }
    /**
     * Creates a new instance of the `AddSubAccountMarginPermissionReq` class.
     * The builder pattern allows step-by-step construction of a `AddSubAccountMarginPermissionReq` object.
     */
    static builder(): AddSubAccountMarginPermissionReqBuilder {
        return new AddSubAccountMarginPermissionReqBuilder(new AddSubAccountMarginPermissionReq());
    }

    /**
     * Creates a new instance of the `AddSubAccountMarginPermissionReq` class with the given data.
     */
    static create(data: {
        /**
         * Sub account UID
         */
        uid: string;
    }): AddSubAccountMarginPermissionReq {
        let obj = new AddSubAccountMarginPermissionReq();
        obj.uid = data.uid;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): AddSubAccountMarginPermissionReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): AddSubAccountMarginPermissionReq {
        return plainToClassFromExist(new AddSubAccountMarginPermissionReq(), jsonObject);
    }
}

export class AddSubAccountMarginPermissionReqBuilder {
    constructor(readonly obj: AddSubAccountMarginPermissionReq) {
        this.obj = obj;
    }
    /**
     * Sub account UID
     */
    setUid(value: string): AddSubAccountMarginPermissionReqBuilder {
        this.obj.uid = value;
        return this;
    }

    build(): AddSubAccountMarginPermissionReq {
        return this.obj;
    }
}
