// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetSpotSubAccountsSummaryV2Items } from './model_get_spot_sub_accounts_summary_v2_items';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetSpotSubAccountsSummaryV2Resp
    implements Response<GetSpotSubAccountsSummaryV2Resp, RestResponse>
{
    /**
     * Current request page
     */
    currentPage?: number;
    /**
     * Number of results per request. Minimum is 1, maximum is 100
     */
    pageSize?: number;
    /**
     * Total number of messages
     */
    totalNum?: number;
    /**
     * Total number of page
     */
    totalPage?: number;
    /**
     *
     */
    @Type(() => GetSpotSubAccountsSummaryV2Items)
    items?: Array<GetSpotSubAccountsSummaryV2Items>;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetSpotSubAccountsSummaryV2Resp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetSpotSubAccountsSummaryV2Resp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetSpotSubAccountsSummaryV2Resp {
        return plainToInstance(GetSpotSubAccountsSummaryV2Resp, jsonObject);
    }
}
