// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class ModifySubAccountApiReq implements Serializable {
    /**
     * Password(Must contain 7-32 characters. Cannot contain any spaces.)
     */
    passphrase: string;

    /**
     * [Permissions](https://www.kucoin.com/docs-new/doc-338144)(Only General、Spot、Futures、Margin、InnerTransfer(Flex Transfer) permissions can be set, such as \"General, Trade\". The default is \"General\")
     */
    permission?: string = 'General';

    /**
     * IP whitelist(You may add up to 20 IPs. Use a halfwidth comma to each IP)
     */
    ipWhitelist?: string;

    /**
     * API expiration time; Never expire(default)-1，30Day30，90Day90，180Day180，360Day360
     */
    expire?: ModifySubAccountApiReq.ExpireEnum = ModifySubAccountApiReq.ExpireEnum._1;

    /**
     * Sub-account name, create sub account name of API Key.
     */
    subName: string;

    /**
     * API-Key(Sub-account APIKey)
     */
    apiKey: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.passphrase = null;
        // @ts-ignore
        this.subName = null;
        // @ts-ignore
        this.apiKey = null;
    }
    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class.
     * The builder pattern allows step-by-step construction of a `ModifySubAccountApiReq` object.
     */
    static builder(): ModifySubAccountApiReqBuilder {
        return new ModifySubAccountApiReqBuilder(new ModifySubAccountApiReq());
    }

    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class with the given data.
     */
    static create(data: {
        /**
         * Password(Must contain 7-32 characters. Cannot contain any spaces.)
         */
        passphrase: string;
        /**
         * [Permissions](https://www.kucoin.com/docs-new/doc-338144)(Only General、Spot、Futures、Margin、InnerTransfer(Flex Transfer) permissions can be set, such as \"General, Trade\". The default is \"General\")
         */
        permission?: string;
        /**
         * IP whitelist(You may add up to 20 IPs. Use a halfwidth comma to each IP)
         */
        ipWhitelist?: string;
        /**
         * API expiration time; Never expire(default)-1，30Day30，90Day90，180Day180，360Day360
         */
        expire?: ModifySubAccountApiReq.ExpireEnum;
        /**
         * Sub-account name, create sub account name of API Key.
         */
        subName: string;
        /**
         * API-Key(Sub-account APIKey)
         */
        apiKey: string;
    }): ModifySubAccountApiReq {
        let obj = new ModifySubAccountApiReq();
        obj.passphrase = data.passphrase;
        if (data.permission) {
            obj.permission = data.permission;
        } else {
            obj.permission = 'General';
        }
        obj.ipWhitelist = data.ipWhitelist;
        if (data.expire) {
            obj.expire = data.expire;
        } else {
            obj.expire = ModifySubAccountApiReq.ExpireEnum._1;
        }
        obj.subName = data.subName;
        obj.apiKey = data.apiKey;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): ModifySubAccountApiReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): ModifySubAccountApiReq {
        return plainToClassFromExist(new ModifySubAccountApiReq(), jsonObject);
    }
}

export namespace ModifySubAccountApiReq {
    export enum ExpireEnum {
        /**
         *
         */
        _1 = <any>'-1',
        /**
         *
         */
        _30 = <any>'30',
        /**
         *
         */
        _90 = <any>'90',
        /**
         *
         */
        _180 = <any>'180',
        /**
         *
         */
        _360 = <any>'360',
    }
}

export class ModifySubAccountApiReqBuilder {
    constructor(readonly obj: ModifySubAccountApiReq) {
        this.obj = obj;
    }
    /**
     * Password(Must contain 7-32 characters. Cannot contain any spaces.)
     */
    setPassphrase(value: string): ModifySubAccountApiReqBuilder {
        this.obj.passphrase = value;
        return this;
    }

    /**
     * [Permissions](https://www.kucoin.com/docs-new/doc-338144)(Only General、Spot、Futures、Margin、InnerTransfer(Flex Transfer) permissions can be set, such as \"General, Trade\". The default is \"General\")
     */
    setPermission(value: string): ModifySubAccountApiReqBuilder {
        this.obj.permission = value;
        return this;
    }

    /**
     * IP whitelist(You may add up to 20 IPs. Use a halfwidth comma to each IP)
     */
    setIpWhitelist(value: string): ModifySubAccountApiReqBuilder {
        this.obj.ipWhitelist = value;
        return this;
    }

    /**
     * API expiration time; Never expire(default)-1，30Day30，90Day90，180Day180，360Day360
     */
    setExpire(value: ModifySubAccountApiReq.ExpireEnum): ModifySubAccountApiReqBuilder {
        this.obj.expire = value;
        return this;
    }

    /**
     * Sub-account name, create sub account name of API Key.
     */
    setSubName(value: string): ModifySubAccountApiReqBuilder {
        this.obj.subName = value;
        return this;
    }

    /**
     * API-Key(Sub-account APIKey)
     */
    setApiKey(value: string): ModifySubAccountApiReqBuilder {
        this.obj.apiKey = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): ModifySubAccountApiReq {
        return this.obj;
    }
}
