// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { GetSpotSubAccountListV2ItemsMarginAccounts } from './model_get_spot_sub_account_list_v2_items_margin_accounts';
import { Type, instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { GetSpotSubAccountListV2ItemsMainAccounts } from './model_get_spot_sub_account_list_v2_items_main_accounts';
import { GetSpotSubAccountListV2ItemsTradeAccounts } from './model_get_spot_sub_account_list_v2_items_trade_accounts';
import { Serializable } from '@internal/interfaces/serializable';

export class GetSpotSubAccountListV2Items implements Serializable {
    /**
     * The user ID of the sub-user.
     */
    subUserId: string;

    /**
     * The username of the sub-user.
     */
    subName: string;

    /**
     * Funding Account
     */
    @Type(() => GetSpotSubAccountListV2ItemsMainAccounts)
    mainAccounts: Array<GetSpotSubAccountListV2ItemsMainAccounts>;

    /**
     * Spot Account
     */
    @Type(() => GetSpotSubAccountListV2ItemsTradeAccounts)
    tradeAccounts: Array<GetSpotSubAccountListV2ItemsTradeAccounts>;

    /**
     * Margin Account
     */
    @Type(() => GetSpotSubAccountListV2ItemsMarginAccounts)
    marginAccounts: Array<GetSpotSubAccountListV2ItemsMarginAccounts>;

    /**
     * This param is deprecated and only valid for some old users
     */
    tradeHFAccounts: Array<string>;

    private constructor() {
        // @ts-ignore
        this.subUserId = null;
        // @ts-ignore
        this.subName = null;
        // @ts-ignore
        this.mainAccounts = null;
        // @ts-ignore
        this.tradeAccounts = null;
        // @ts-ignore
        this.marginAccounts = null;
        // @ts-ignore
        this.tradeHFAccounts = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetSpotSubAccountListV2Items {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetSpotSubAccountListV2Items {
        return plainToClassFromExist(new GetSpotSubAccountListV2Items(), jsonObject);
    }
}
