// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { GetIsolatedMarginAccountListV1AssetsBaseAsset } from './model_get_isolated_margin_account_list_v1_assets_base_asset';
import { GetIsolatedMarginAccountListV1AssetsQuoteAsset } from './model_get_isolated_margin_account_list_v1_assets_quote_asset';
import { Serializable } from '@internal/interfaces/serializable';

export class GetIsolatedMarginAccountListV1Assets implements Serializable {
    /**
     * Symbol
     */
    symbol: string;

    /**
     * The position status: Existing liabilities-DEBT, No liabilities-CLEAR, Bankrupcy (after position enters a negative balance)-BANKRUPTCY, Existing borrowings-IN_BORROW, Existing repayments-IN_REPAY, Under liquidation-IN_LIQUIDATION, Under auto-renewal assets-IN_AUTO_RENEW .
     */
    status: GetIsolatedMarginAccountListV1Assets.StatusEnum;

    /**
     * debt ratio
     */
    debtRatio: string;

    /**
     *
     */
    @Type(() => GetIsolatedMarginAccountListV1AssetsBaseAsset)
    baseAsset: GetIsolatedMarginAccountListV1AssetsBaseAsset;

    /**
     *
     */
    @Type(() => GetIsolatedMarginAccountListV1AssetsQuoteAsset)
    quoteAsset: GetIsolatedMarginAccountListV1AssetsQuoteAsset;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.status = null;
        // @ts-ignore
        this.debtRatio = null;
        // @ts-ignore
        this.baseAsset = null;
        // @ts-ignore
        this.quoteAsset = null;
    }
    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetIsolatedMarginAccountListV1Assets {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetIsolatedMarginAccountListV1Assets {
        return plainToClassFromExist(new GetIsolatedMarginAccountListV1Assets(), jsonObject);
    }
}

export namespace GetIsolatedMarginAccountListV1Assets {
    export enum StatusEnum {
        /**
         *
         */
        DEBT = <any>'DEBT',
        /**
         *
         */
        CLEAR = <any>'CLEAR',
        /**
         *
         */
        BANKRUPTCY = <any>'BANKRUPTCY',
        /**
         *
         */
        IN_BORROW = <any>'IN_BORROW',
        /**
         *
         */
        IN_REPAY = <any>'IN_REPAY',
        /**
         *
         */
        IN_LIQUIDATION = <any>'IN_LIQUIDATION',
        /**
         *
         */
        IN_AUTO_RENEW = <any>'IN_AUTO_RENEW',
    }
}
