// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetIsolatedMarginAccountDetailV1Req implements Serializable {
    /**
     *
     */
    @Reflect.metadata('path', 'symbol')
    symbol?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetIsolatedMarginAccountDetailV1Req` class.
     * The builder pattern allows step-by-step construction of a `GetIsolatedMarginAccountDetailV1Req` object.
     */
    static builder(): GetIsolatedMarginAccountDetailV1ReqBuilder {
        return new GetIsolatedMarginAccountDetailV1ReqBuilder(
            new GetIsolatedMarginAccountDetailV1Req(),
        );
    }

    /**
     * Creates a new instance of the `GetIsolatedMarginAccountDetailV1Req` class with the given data.
     */
    static create(data: {
        /**
         *
         */
        symbol?: string;
    }): GetIsolatedMarginAccountDetailV1Req {
        let obj = new GetIsolatedMarginAccountDetailV1Req();
        obj.symbol = data.symbol;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetIsolatedMarginAccountDetailV1Req {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetIsolatedMarginAccountDetailV1Req {
        return plainToClassFromExist(new GetIsolatedMarginAccountDetailV1Req(), jsonObject);
    }
}

export class GetIsolatedMarginAccountDetailV1ReqBuilder {
    constructor(readonly obj: GetIsolatedMarginAccountDetailV1Req) {
        this.obj = obj;
    }
    /**
     *
     */
    setSymbol(value: string): GetIsolatedMarginAccountDetailV1ReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetIsolatedMarginAccountDetailV1Req {
        return this.obj;
    }
}
