// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetSpotLedgerItems implements Serializable {
    /**
     * unique id
     */
    id?: string;

    /**
     * The currency of an account
     */
    currency?: string;

    /**
     * The total amount of assets (fees included) involved in assets changes such as transaction, withdrawal and bonus distribution.
     */
    amount?: string;

    /**
     * Fees generated in transaction, withdrawal, etc.
     */
    fee?: string;

    /**
     * Remaining funds after the transaction.
     */
    balance?: string;

    /**
     * The account type of the master user: MAIN, TRADE, MARGIN or CONTRACT.
     */
    accountType?: string;

    /**
     * Business type leading to the changes in funds, such as exchange, withdrawal, deposit, KUCOIN_BONUS, REFERRAL_BONUS, Lendings etc.
     */
    bizType?: string;

    /**
     * Side, out or in
     */
    direction?: string;

    /**
     * Time of the event
     */
    createdAt?: number;

    /**
     * Business related information such as order ID, serial No., etc.
     */
    context?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetSpotLedgerItems {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetSpotLedgerItems {
        return plainToClassFromExist(new GetSpotLedgerItems(), jsonObject);
    }
}
