// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetIsolatedMarginAccountListV1Req
    implements Serializable<GetIsolatedMarginAccountListV1Req>
{
    /**
     * quote currency, currently only supports USDT, KCS, BTC, USDT as default
     */
    balanceCurrency?: GetIsolatedMarginAccountListV1Req.BalanceCurrencyEnum =
        GetIsolatedMarginAccountListV1Req.BalanceCurrencyEnum.BTC;

    /**
     * Creates a new instance of the `GetIsolatedMarginAccountListV1Req` class.
     * The builder pattern allows step-by-step construction of a `GetIsolatedMarginAccountListV1Req` object.
     */
    static builder(): GetIsolatedMarginAccountListV1ReqBuilder {
        return new GetIsolatedMarginAccountListV1ReqBuilder();
    }

    /**
     * Creates a new instance of the `GetIsolatedMarginAccountListV1Req` class with the given data.
     */
    static create(data: {
        /**
         * quote currency, currently only supports USDT, KCS, BTC, USDT as default
         */
        balanceCurrency?: GetIsolatedMarginAccountListV1Req.BalanceCurrencyEnum;
    }): GetIsolatedMarginAccountListV1Req {
        let obj = new GetIsolatedMarginAccountListV1Req();
        obj.balanceCurrency = data.balanceCurrency;
        return obj;
    }

    fromJson(input: string): GetIsolatedMarginAccountListV1Req {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetIsolatedMarginAccountListV1Req, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetIsolatedMarginAccountListV1Req {
        return plainToInstance(GetIsolatedMarginAccountListV1Req, jsonObject);
    }
}

export namespace GetIsolatedMarginAccountListV1Req {
    export enum BalanceCurrencyEnum {
        /**
         *
         */
        USDT = <any>'USDT',
        /**
         *
         */
        KCS = <any>'KCS',
        /**
         *
         */
        BTC = <any>'BTC',
    }
}

export class GetIsolatedMarginAccountListV1ReqBuilder {
    obj: GetIsolatedMarginAccountListV1Req = new GetIsolatedMarginAccountListV1Req();
    /**
     * quote currency, currently only supports USDT, KCS, BTC, USDT as default
     */
    setBalanceCurrency(
        value: GetIsolatedMarginAccountListV1Req.BalanceCurrencyEnum,
    ): GetIsolatedMarginAccountListV1ReqBuilder {
        this.obj.balanceCurrency = value;
        return this;
    }

    build(): GetIsolatedMarginAccountListV1Req {
        return this.obj;
    }
}
