// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetCrossMarginAccountReq implements Serializable {
    /**
     * quote currency, currently only supports USDT, KCS, BTC, USDT as default
     */
    quoteCurrency?: GetCrossMarginAccountReq.QuoteCurrencyEnum =
        GetCrossMarginAccountReq.QuoteCurrencyEnum.USDT;

    /**
     * Query account type (default MARGIN), MARGIN - only query low frequency cross margin account, MARGIN_V2-only query high frequency cross margin account, ALL - consistent aggregate query with the web side
     */
    queryType?: GetCrossMarginAccountReq.QueryTypeEnum =
        GetCrossMarginAccountReq.QueryTypeEnum.MARGIN;

    private constructor() {}
    /**
     * Creates a new instance of the `GetCrossMarginAccountReq` class.
     * The builder pattern allows step-by-step construction of a `GetCrossMarginAccountReq` object.
     */
    static builder(): GetCrossMarginAccountReqBuilder {
        return new GetCrossMarginAccountReqBuilder(new GetCrossMarginAccountReq());
    }

    /**
     * Creates a new instance of the `GetCrossMarginAccountReq` class with the given data.
     */
    static create(data: {
        /**
         * quote currency, currently only supports USDT, KCS, BTC, USDT as default
         */
        quoteCurrency?: GetCrossMarginAccountReq.QuoteCurrencyEnum;
        /**
         * Query account type (default MARGIN), MARGIN - only query low frequency cross margin account, MARGIN_V2-only query high frequency cross margin account, ALL - consistent aggregate query with the web side
         */
        queryType?: GetCrossMarginAccountReq.QueryTypeEnum;
    }): GetCrossMarginAccountReq {
        let obj = new GetCrossMarginAccountReq();
        if (data.quoteCurrency) {
            obj.quoteCurrency = data.quoteCurrency;
        } else {
            obj.quoteCurrency = GetCrossMarginAccountReq.QuoteCurrencyEnum.USDT;
        }
        if (data.queryType) {
            obj.queryType = data.queryType;
        } else {
            obj.queryType = GetCrossMarginAccountReq.QueryTypeEnum.MARGIN;
        }
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetCrossMarginAccountReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetCrossMarginAccountReq {
        return plainToClassFromExist(new GetCrossMarginAccountReq(), jsonObject);
    }
}

export namespace GetCrossMarginAccountReq {
    export enum QuoteCurrencyEnum {
        /**
         *
         */
        USDT = <any>'USDT',
        /**
         *
         */
        KCS = <any>'KCS',
        /**
         *
         */
        BTC = <any>'BTC',
    }
    export enum QueryTypeEnum {
        /**
         *
         */
        MARGIN = <any>'MARGIN',
        /**
         *
         */
        MARGIN_V2 = <any>'MARGIN_V2',
        /**
         *
         */
        ALL = <any>'ALL',
    }
}

export class GetCrossMarginAccountReqBuilder {
    constructor(readonly obj: GetCrossMarginAccountReq) {
        this.obj = obj;
    }
    /**
     * quote currency, currently only supports USDT, KCS, BTC, USDT as default
     */
    setQuoteCurrency(
        value: GetCrossMarginAccountReq.QuoteCurrencyEnum,
    ): GetCrossMarginAccountReqBuilder {
        this.obj.quoteCurrency = value;
        return this;
    }

    /**
     * Query account type (default MARGIN), MARGIN - only query low frequency cross margin account, MARGIN_V2-only query high frequency cross margin account, ALL - consistent aggregate query with the web side
     */
    setQueryType(value: GetCrossMarginAccountReq.QueryTypeEnum): GetCrossMarginAccountReqBuilder {
        this.obj.queryType = value;
        return this;
    }

    build(): GetCrossMarginAccountReq {
        return this.obj;
    }
}
