// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';
export class GetIsolatedMarginAccountDetailV1Req
    implements Serializable<GetIsolatedMarginAccountDetailV1Req>
{
    /**
     *
     */
    @Reflect.metadata('path', 'symbol')
    symbol?: string;

    /**
     * Creates a new instance of the `GetIsolatedMarginAccountDetailV1Req` class.
     * The builder pattern allows step-by-step construction of a `GetIsolatedMarginAccountDetailV1Req` object.
     */
    static builder(): GetIsolatedMarginAccountDetailV1ReqBuilder {
        return new GetIsolatedMarginAccountDetailV1ReqBuilder();
    }

    /**
     * Creates a new instance of the `GetIsolatedMarginAccountDetailV1Req` class with the given data.
     */
    static create(data: {
        /**
         *
         */
        symbol?: string;
    }): GetIsolatedMarginAccountDetailV1Req {
        let obj = new GetIsolatedMarginAccountDetailV1Req();
        obj.symbol = data.symbol;
        return obj;
    }

    fromJson(input: string): GetIsolatedMarginAccountDetailV1Req {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetIsolatedMarginAccountDetailV1Req, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetIsolatedMarginAccountDetailV1Req {
        return plainToInstance(GetIsolatedMarginAccountDetailV1Req, jsonObject);
    }
}

export class GetIsolatedMarginAccountDetailV1ReqBuilder {
    obj: GetIsolatedMarginAccountDetailV1Req = new GetIsolatedMarginAccountDetailV1Req();
    /**
     *
     */
    setSymbol(value: string): GetIsolatedMarginAccountDetailV1ReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): GetIsolatedMarginAccountDetailV1Req {
        return this.obj;
    }
}
