// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetFuturesLedgerDataList } from './model_get_futures_ledger_data_list';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetFuturesLedgerResp implements Response<GetFuturesLedgerResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetFuturesLedgerDataList)
    dataList?: Array<GetFuturesLedgerDataList>;
    /**
     * Is it the last page. If it is false, it means it is the last page, and if it is true, it means need to turn the page.
     */
    hasMore?: boolean;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetFuturesLedgerResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetFuturesLedgerResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetFuturesLedgerResp {
        return plainToInstance(GetFuturesLedgerResp, jsonObject);
    }
}
