// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetSpotIndexPriceDataList } from './model_get_spot_index_price_data_list';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetSpotIndexPriceResp implements Response<GetSpotIndexPriceResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetSpotIndexPriceDataList)
    dataList?: Array<GetSpotIndexPriceDataList>;
    /**
     * Whether there are more pages
     */
    hasMore?: boolean;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetSpotIndexPriceResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetSpotIndexPriceResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetSpotIndexPriceResp {
        return plainToInstance(GetSpotIndexPriceResp, jsonObject);
    }
}
