// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetPrivateTokenInstanceServers } from './model_get_private_token_instance_servers';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetPrivateTokenResp implements Response<GetPrivateTokenResp, RestResponse> {
    /**
     * The token required to establish a websocket connection
     */
    token?: string;
    /**
     *
     */
    @Type(() => GetPrivateTokenInstanceServers)
    instanceServers?: Array<GetPrivateTokenInstanceServers>;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetPrivateTokenResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetPrivateTokenResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetPrivateTokenResp {
        return plainToInstance(GetPrivateTokenResp, jsonObject);
    }
}
