// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetInterestRateIndexDataList } from './model_get_interest_rate_index_data_list';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetInterestRateIndexResp implements Response<GetInterestRateIndexResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetInterestRateIndexDataList)
    dataList?: Array<GetInterestRateIndexDataList>;
    /**
     * Whether there are more pages
     */
    hasMore?: boolean;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetInterestRateIndexResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetInterestRateIndexResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetInterestRateIndexResp {
        return plainToInstance(GetInterestRateIndexResp, jsonObject);
    }
}
