// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetMarkPriceReq implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    @Reflect.metadata('path', 'symbol')
    symbol?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetMarkPriceReq` class.
     * The builder pattern allows step-by-step construction of a `GetMarkPriceReq` object.
     */
    static builder(): GetMarkPriceReqBuilder {
        return new GetMarkPriceReqBuilder(new GetMarkPriceReq());
    }

    /**
     * Creates a new instance of the `GetMarkPriceReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
    }): GetMarkPriceReq {
        let obj = new GetMarkPriceReq();
        obj.symbol = data.symbol;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetMarkPriceReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetMarkPriceReq {
        return plainToClassFromExist(new GetMarkPriceReq(), jsonObject);
    }
}

export class GetMarkPriceReqBuilder {
    constructor(readonly obj: GetMarkPriceReq) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetMarkPriceReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetMarkPriceReq {
        return this.obj;
    }
}
