// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetPartOrderBookReq implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * Get the depth layer, optional value: 20, 100
     */
    @Reflect.metadata('path', 'size')
    size?: string;

    private constructor() {}
    /**
     * Creates a new instance of the `GetPartOrderBookReq` class.
     * The builder pattern allows step-by-step construction of a `GetPartOrderBookReq` object.
     */
    static builder(): GetPartOrderBookReqBuilder {
        return new GetPartOrderBookReqBuilder(new GetPartOrderBookReq());
    }

    /**
     * Creates a new instance of the `GetPartOrderBookReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
        /**
         * Get the depth layer, optional value: 20, 100
         */
        size?: string;
    }): GetPartOrderBookReq {
        let obj = new GetPartOrderBookReq();
        obj.symbol = data.symbol;
        obj.size = data.size;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetPartOrderBookReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetPartOrderBookReq {
        return plainToClassFromExist(new GetPartOrderBookReq(), jsonObject);
    }
}

export class GetPartOrderBookReqBuilder {
    constructor(readonly obj: GetPartOrderBookReq) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetPartOrderBookReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Get the depth layer, optional value: 20, 100
     */
    setSize(value: string): GetPartOrderBookReqBuilder {
        this.obj.size = value;
        return this;
    }

    build(): GetPartOrderBookReq {
        return this.obj;
    }
}
