// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetAllTickersData } from './model_get_all_tickers_data';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetAllTickersResp implements Response<GetAllTickersResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetAllTickersData)
    data?: Array<GetAllTickersData>;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetAllTickersResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetAllTickersResp, { data: jsonObject });
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }

    fromObject(jsonObject: Object): GetAllTickersResp {
        return plainToInstance(GetAllTickersResp, { data: jsonObject });
    }
}
