// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetLoanMarketInterestRateReq implements Serializable {
    /**
     * currency
     */
    currency?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetLoanMarketInterestRateReq` class.
     * The builder pattern allows step-by-step construction of a `GetLoanMarketInterestRateReq` object.
     */
    static builder(): GetLoanMarketInterestRateReqBuilder {
        return new GetLoanMarketInterestRateReqBuilder(new GetLoanMarketInterestRateReq());
    }

    /**
     * Creates a new instance of the `GetLoanMarketInterestRateReq` class with the given data.
     */
    static create(data: {
        /**
         * currency
         */
        currency?: string;
    }): GetLoanMarketInterestRateReq {
        let obj = new GetLoanMarketInterestRateReq();
        obj.currency = data.currency;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetLoanMarketInterestRateReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetLoanMarketInterestRateReq {
        return plainToClassFromExist(new GetLoanMarketInterestRateReq(), jsonObject);
    }
}

export class GetLoanMarketInterestRateReqBuilder {
    constructor(readonly obj: GetLoanMarketInterestRateReq) {
        this.obj = obj;
    }
    /**
     * currency
     */
    setCurrency(value: string): GetLoanMarketInterestRateReqBuilder {
        this.obj.currency = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetLoanMarketInterestRateReq {
        return this.obj;
    }
}
