// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetLoanMarketInterestRateData implements Serializable {
    /**
     * Time: YYYYMMDDHH00
     */
    time: string;

    /**
     * Market lending rate
     */
    marketInterestRate: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.time = null;
        // @ts-ignore
        this.marketInterestRate = null;
    }
    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetLoanMarketInterestRateData {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetLoanMarketInterestRateData {
        return plainToClassFromExist(new GetLoanMarketInterestRateData(), jsonObject);
    }
}
