// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetWithdrawalHistoryItems implements Serializable<GetWithdrawalHistoryItems> {
    /**
     * Unique id
     */
    id?: string;
    /**
     * Currency
     */
    currency?: string;
    /**
     * The id of currency
     */
    chain?: string;
    /**
     * Status
     */
    status?: GetWithdrawalHistoryItems.StatusEnum;
    /**
     * Deposit address
     */
    address?: string;
    /**
     * Address remark. If there’s no remark, it is empty.
     */
    memo?: string;
    /**
     * Internal deposit or not
     */
    isInner?: boolean;
    /**
     * Deposit amount
     */
    amount?: string;
    /**
     * Fees charged for deposit
     */
    fee?: string;
    /**
     * Wallet Txid
     */
    walletTxId?: string;
    /**
     * Creation time of the database record
     */
    createdAt?: number;
    /**
     * Update time of the database record
     */
    updatedAt?: number;
    /**
     * remark
     */
    remark?: string;

    fromJson(input: string): GetWithdrawalHistoryItems {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetWithdrawalHistoryItems, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetWithdrawalHistoryItems {
        return plainToInstance(GetWithdrawalHistoryItems, jsonObject);
    }
}

export namespace GetWithdrawalHistoryItems {
    export enum StatusEnum {
        /**
         *
         */
        PROCESSING = <any>'PROCESSING',
        /**
         *
         */
        WALLET_PROCESSING = <any>'WALLET_PROCESSING',
        /**
         *
         */
        SUCCESS = <any>'SUCCESS',
        /**
         *
         */
        FAILURE = <any>'FAILURE',
    }
}
