// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class WithdrawalV3Req implements Serializable<WithdrawalV3Req> {
    /**
     * currency
     */
    currency?: string;
    /**
     * The chainId of currency, For a currency with multiple chains, it is recommended to specify chain parameter instead of using the default chain; you can query the chainId through the response of the GET /api/v3/currencies/{currency} interface.
     */
    chain?: string = 'eth';
    /**
     * Withdrawal amount, a positive number which is a multiple of the amount precision
     */
    amount?: number;
    /**
     * Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to the KuCoin, you need to fill in memo(tag). If you do not fill memo (tag), your deposit may not be available, please be cautious.
     */
    memo?: string;
    /**
     * Internal withdrawal or not. Default : false
     */
    isInner?: boolean = false;
    /**
     * remark
     */
    remark?: string;
    /**
     * Withdrawal fee deduction type: INTERNAL or EXTERNAL or not specified  1. INTERNAL- deduct the transaction fees from your withdrawal amount 2. EXTERNAL- deduct the transaction fees from your main account 3. If you don\'t specify the feeDeductType parameter, when the balance in your main account is sufficient to support the withdrawal, the system will initially deduct the transaction fees from your main account. But if the balance in your main account is not sufficient to support the withdrawal, the system will deduct the fees from your withdrawal amount. For example: Suppose you are going to withdraw 1 BTC from the KuCoin platform (transaction fee: 0.0001BTC), if the balance in your main account is insufficient, the system will deduct the transaction fees from your withdrawal amount. In this case, you will be receiving 0.9999BTC.
     */
    feeDeductType?: string;
    /**
     * Withdrawal address
     */
    toAddress?: string;
    /**
     * Withdrawal type, ADDRESS (withdrawal address), UID, MAIL (email), PHONE (mobile phone number). Note: If you withdraw by uid/mail/phone, there will have rate limited: 3 times/10 seconds, 50 times/24 hours (calculated on a rolling basis based on the first request time)
     */
    withdrawType?: WithdrawalV3Req.WithdrawTypeEnum;

    /**
     * Creates a new instance of the `WithdrawalV3Req` class.
     * The builder pattern allows step-by-step construction of a `WithdrawalV3Req` object.
     */
    static builder(): WithdrawalV3ReqBuilder {
        return new WithdrawalV3ReqBuilder();
    }

    /**
     * Creates a new instance of the `WithdrawalV3Req` class with the given data.
     */
    static create(data: {
        /**
         * currency
         */
        currency?: string;
        /**
         * The chainId of currency, For a currency with multiple chains, it is recommended to specify chain parameter instead of using the default chain; you can query the chainId through the response of the GET /api/v3/currencies/{currency} interface.
         */
        chain?: string;
        /**
         * Withdrawal amount, a positive number which is a multiple of the amount precision
         */
        amount?: number;
        /**
         * Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to the KuCoin, you need to fill in memo(tag). If you do not fill memo (tag), your deposit may not be available, please be cautious.
         */
        memo?: string;
        /**
         * Internal withdrawal or not. Default : false
         */
        isInner?: boolean;
        /**
         * remark
         */
        remark?: string;
        /**
         * Withdrawal fee deduction type: INTERNAL or EXTERNAL or not specified  1. INTERNAL- deduct the transaction fees from your withdrawal amount 2. EXTERNAL- deduct the transaction fees from your main account 3. If you don\'t specify the feeDeductType parameter, when the balance in your main account is sufficient to support the withdrawal, the system will initially deduct the transaction fees from your main account. But if the balance in your main account is not sufficient to support the withdrawal, the system will deduct the fees from your withdrawal amount. For example: Suppose you are going to withdraw 1 BTC from the KuCoin platform (transaction fee: 0.0001BTC), if the balance in your main account is insufficient, the system will deduct the transaction fees from your withdrawal amount. In this case, you will be receiving 0.9999BTC.
         */
        feeDeductType?: string;
        /**
         * Withdrawal address
         */
        toAddress?: string;
        /**
         * Withdrawal type, ADDRESS (withdrawal address), UID, MAIL (email), PHONE (mobile phone number). Note: If you withdraw by uid/mail/phone, there will have rate limited: 3 times/10 seconds, 50 times/24 hours (calculated on a rolling basis based on the first request time)
         */
        withdrawType?: WithdrawalV3Req.WithdrawTypeEnum;
    }): WithdrawalV3Req {
        let obj = new WithdrawalV3Req();
        obj.currency = data.currency;
        obj.chain = data.chain;
        obj.amount = data.amount;
        obj.memo = data.memo;
        obj.isInner = data.isInner;
        obj.remark = data.remark;
        obj.feeDeductType = data.feeDeductType;
        obj.toAddress = data.toAddress;
        obj.withdrawType = data.withdrawType;
        return obj;
    }

    fromJson(input: string): WithdrawalV3Req {
        const jsonObject = JSON.parse(input);
        return plainToInstance(WithdrawalV3Req, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): WithdrawalV3Req {
        return plainToInstance(WithdrawalV3Req, jsonObject);
    }
}

export namespace WithdrawalV3Req {
    export enum WithdrawTypeEnum {
        /**
         *
         */
        ADDRESS = <any>'ADDRESS',
        /**
         *
         */
        UID = <any>'UID',
        /**
         *
         */
        MAIL = <any>'MAIL',
        /**
         *
         */
        PHONE = <any>'PHONE',
    }
}

export class WithdrawalV3ReqBuilder {
    obj: WithdrawalV3Req = new WithdrawalV3Req();
    /**
     * currency
     */
    setCurrency(value: string): WithdrawalV3ReqBuilder {
        this.obj.currency = value;
        return this;
    }

    /**
     * The chainId of currency, For a currency with multiple chains, it is recommended to specify chain parameter instead of using the default chain; you can query the chainId through the response of the GET /api/v3/currencies/{currency} interface.
     */
    setChain(value: string): WithdrawalV3ReqBuilder {
        this.obj.chain = value;
        return this;
    }

    /**
     * Withdrawal amount, a positive number which is a multiple of the amount precision
     */
    setAmount(value: number): WithdrawalV3ReqBuilder {
        this.obj.amount = value;
        return this;
    }

    /**
     * Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to the KuCoin, you need to fill in memo(tag). If you do not fill memo (tag), your deposit may not be available, please be cautious.
     */
    setMemo(value: string): WithdrawalV3ReqBuilder {
        this.obj.memo = value;
        return this;
    }

    /**
     * Internal withdrawal or not. Default : false
     */
    setIsInner(value: boolean): WithdrawalV3ReqBuilder {
        this.obj.isInner = value;
        return this;
    }

    /**
     * remark
     */
    setRemark(value: string): WithdrawalV3ReqBuilder {
        this.obj.remark = value;
        return this;
    }

    /**
     * Withdrawal fee deduction type: INTERNAL or EXTERNAL or not specified  1. INTERNAL- deduct the transaction fees from your withdrawal amount 2. EXTERNAL- deduct the transaction fees from your main account 3. If you don\'t specify the feeDeductType parameter, when the balance in your main account is sufficient to support the withdrawal, the system will initially deduct the transaction fees from your main account. But if the balance in your main account is not sufficient to support the withdrawal, the system will deduct the fees from your withdrawal amount. For example: Suppose you are going to withdraw 1 BTC from the KuCoin platform (transaction fee: 0.0001BTC), if the balance in your main account is insufficient, the system will deduct the transaction fees from your withdrawal amount. In this case, you will be receiving 0.9999BTC.
     */
    setFeeDeductType(value: string): WithdrawalV3ReqBuilder {
        this.obj.feeDeductType = value;
        return this;
    }

    /**
     * Withdrawal address
     */
    setToAddress(value: string): WithdrawalV3ReqBuilder {
        this.obj.toAddress = value;
        return this;
    }

    /**
     * Withdrawal type, ADDRESS (withdrawal address), UID, MAIL (email), PHONE (mobile phone number). Note: If you withdraw by uid/mail/phone, there will have rate limited: 3 times/10 seconds, 50 times/24 hours (calculated on a rolling basis based on the first request time)
     */
    setWithdrawType(value: WithdrawalV3Req.WithdrawTypeEnum): WithdrawalV3ReqBuilder {
        this.obj.withdrawType = value;
        return this;
    }

    build(): WithdrawalV3Req {
        return this.obj;
    }
}
