// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class WithdrawalV3Resp implements Response<WithdrawalV3Resp, RestResponse> {
    /**
     * Withdrawal id, a unique ID for a withdrawal
     */
    withdrawalId?: string;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): WithdrawalV3Resp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(WithdrawalV3Resp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): WithdrawalV3Resp {
        return plainToInstance(WithdrawalV3Resp, jsonObject);
    }
}
