// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetWithdrawalHistoryItems } from './model_get_withdrawal_history_items';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetWithdrawalHistoryResp implements Response<GetWithdrawalHistoryResp, RestResponse> {
    /**
     * current page
     */
    currentPage?: number;
    /**
     * page size
     */
    pageSize?: number;
    /**
     * total number
     */
    totalNum?: number;
    /**
     * total page
     */
    totalPage?: number;
    /**
     *
     */
    @Type(() => GetWithdrawalHistoryItems)
    items?: Array<GetWithdrawalHistoryItems>;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetWithdrawalHistoryResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetWithdrawalHistoryResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetWithdrawalHistoryResp {
        return plainToInstance(GetWithdrawalHistoryResp, jsonObject);
    }
}
