// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class CancelOrderByClientOidOldResp
    implements Response<CancelOrderByClientOidOldResp, RestResponse>
{
    /**
     * Client Order Id，unique identifier created by the user
     */
    clientOid?: string;
    /**
     *
     */
    cancelledOrderId?: string;
    /**
     *
     */
    cancelledOcoOrderIds?: string;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): CancelOrderByClientOidOldResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(CancelOrderByClientOidOldResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): CancelOrderByClientOidOldResp {
        return plainToInstance(CancelOrderByClientOidOldResp, jsonObject);
    }
}
