// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { GetTradeHistoryItems } from './model_get_trade_history_items';
import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetTradeHistoryResp implements Response<RestResponse> {
    /**
     *
     */
    @Type(() => GetTradeHistoryItems)
    items: Array<GetTradeHistoryItems>;

    /**
     * The id of the last set of data from the previous batch of data. By default, the latest information is given. lastId is used to filter data and paginate. If lastId is not entered, the default is a maximum of 100 returned data items. The return results include lastId，which can be used as a query parameter to look up new data from the next page.
     */
    lastId: number;

    private constructor() {
        // @ts-ignore
        this.items = null;
        // @ts-ignore
        this.lastId = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetTradeHistoryResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetTradeHistoryResp {
        return plainToClassFromExist(new GetTradeHistoryResp(), jsonObject);
    }
}
