// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class CancelOrderByClientOidSyncResp implements Response<RestResponse> {
    /**
     * Client Order Id，unique identifier created by the user
     */
    clientOid: string;

    /**
     * original order size
     */
    originSize: string;

    /**
     * deal size
     */
    dealSize: string;

    /**
     * remain size
     */
    remainSize: string;

    /**
     * Cumulative canceled size
     */
    canceledSize: string;

    /**
     * Order Status. open：order is active; done：order has been completed
     */
    status: CancelOrderByClientOidSyncResp.StatusEnum;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.clientOid = null;
        // @ts-ignore
        this.originSize = null;
        // @ts-ignore
        this.dealSize = null;
        // @ts-ignore
        this.remainSize = null;
        // @ts-ignore
        this.canceledSize = null;
        // @ts-ignore
        this.status = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): CancelOrderByClientOidSyncResp {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): CancelOrderByClientOidSyncResp {
        return plainToClassFromExist(new CancelOrderByClientOidSyncResp(), jsonObject);
    }
}

export namespace CancelOrderByClientOidSyncResp {
    export enum StatusEnum {
        /**
         *
         */
        OPEN = <any>'open',
        /**
         *
         */
        DONE = <any>'done',
    }
}
