// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetDCPResp implements Response<RestResponse> {
    /**
     * Auto cancel order trigger setting time, the unit is second. range: timeout=-1 (meaning unset) or 5 <= timeout <= 86400
     */
    timeout?: number;

    /**
     * List of trading pairs. Separated by commas, empty means all trading pairs
     */
    symbols?: string;

    /**
     * System current time (in seconds)
     */
    currentTime?: number;

    /**
     * Trigger cancellation time (in seconds)
     */
    triggerTime?: number;

    private constructor() {}
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetDCPResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetDCPResp {
        return plainToClassFromExist(new GetDCPResp(), jsonObject);
    }
}
