// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetOcoOrderByOrderIdResp implements Response<GetOcoOrderByOrderIdResp, RestResponse> {
    /**
     * symbol
     */
    symbol?: string;
    /**
     * Client Order Id
     */
    clientOid?: string;
    /**
     * The unique order id generated by the trading system,which can be used later for further actions such as canceling the order.
     */
    orderId?: string;
    /**
     * Order placement time, milliseconds
     */
    orderTime?: number;
    /**
     * Order status: NEW: New, DONE: Completed, TRIGGERED: Triggered, CANCELLED: Cancelled
     */
    status?: GetOcoOrderByOrderIdResp.StatusEnum;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetOcoOrderByOrderIdResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetOcoOrderByOrderIdResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetOcoOrderByOrderIdResp {
        return plainToInstance(GetOcoOrderByOrderIdResp, jsonObject);
    }
}

export namespace GetOcoOrderByOrderIdResp {
    export enum StatusEnum {
        /**
         * New
         */
        NEW = <any>'NEW',
        /**
         * Completed
         */
        DONE = <any>'DONE',
        /**
         * Triggered
         */
        TRIGGERED = <any>'TRIGGERED',
        /**
         * Cancelled
         */
        CANCELLED = <any>'CANCELLED',
    }
}
