// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { BatchAddOrdersSyncData } from './model_batch_add_orders_sync_data';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class BatchAddOrdersSyncResp implements Response<RestResponse> {
    /**
     *
     */
    @Type(() => BatchAddOrdersSyncData)
    data: Array<BatchAddOrdersSyncData>;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.data = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): BatchAddOrdersSyncResp {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): BatchAddOrdersSyncResp {
        return plainToClassFromExist(new BatchAddOrdersSyncResp(), { data: jsonObject });
    }
}
