// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetOrderByClientOidOldReq implements Serializable {
    /**
     * Unique order id created by users to identify their orders
     */
    @Reflect.metadata('path', 'clientOid')
    clientOid?: string;

    private constructor() {}
    /**
     * Creates a new instance of the `GetOrderByClientOidOldReq` class.
     * The builder pattern allows step-by-step construction of a `GetOrderByClientOidOldReq` object.
     */
    static builder(): GetOrderByClientOidOldReqBuilder {
        return new GetOrderByClientOidOldReqBuilder(new GetOrderByClientOidOldReq());
    }

    /**
     * Creates a new instance of the `GetOrderByClientOidOldReq` class with the given data.
     */
    static create(data: {
        /**
         * Unique order id created by users to identify their orders
         */
        clientOid?: string;
    }): GetOrderByClientOidOldReq {
        let obj = new GetOrderByClientOidOldReq();
        obj.clientOid = data.clientOid;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetOrderByClientOidOldReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetOrderByClientOidOldReq {
        return plainToClassFromExist(new GetOrderByClientOidOldReq(), jsonObject);
    }
}

export class GetOrderByClientOidOldReqBuilder {
    constructor(readonly obj: GetOrderByClientOidOldReq) {
        this.obj = obj;
    }
    /**
     * Unique order id created by users to identify their orders
     */
    setClientOid(value: string): GetOrderByClientOidOldReqBuilder {
        this.obj.clientOid = value;
        return this;
    }

    build(): GetOrderByClientOidOldReq {
        return this.obj;
    }
}
