// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class CancelOrderByOrderIdSyncReq implements Serializable<CancelOrderByOrderIdSyncReq> {
    /**
     * The unique order id generated by the trading system
     */
    @Reflect.metadata('path', 'orderId')
    orderId?: string;
    /**
     * symbol
     */
    symbol?: string;

    /**
     * Creates a new instance of the `CancelOrderByOrderIdSyncReq` class.
     * The builder pattern allows step-by-step construction of a `CancelOrderByOrderIdSyncReq` object.
     */
    static builder(): CancelOrderByOrderIdSyncReqBuilder {
        return new CancelOrderByOrderIdSyncReqBuilder();
    }

    /**
     * Creates a new instance of the `CancelOrderByOrderIdSyncReq` class with the given data.
     */
    static create(data: {
        /**
         * The unique order id generated by the trading system
         */
        orderId?: string;
        /**
         * symbol
         */
        symbol?: string;
    }): CancelOrderByOrderIdSyncReq {
        let obj = new CancelOrderByOrderIdSyncReq();
        obj.orderId = data.orderId;
        obj.symbol = data.symbol;
        return obj;
    }

    fromJson(input: string): CancelOrderByOrderIdSyncReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(CancelOrderByOrderIdSyncReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): CancelOrderByOrderIdSyncReq {
        return plainToInstance(CancelOrderByOrderIdSyncReq, jsonObject);
    }
}

export class CancelOrderByOrderIdSyncReqBuilder {
    obj: CancelOrderByOrderIdSyncReq = new CancelOrderByOrderIdSyncReq();
    /**
     * The unique order id generated by the trading system
     */
    setOrderId(value: string): CancelOrderByOrderIdSyncReqBuilder {
        this.obj.orderId = value;
        return this;
    }

    /**
     * symbol
     */
    setSymbol(value: string): CancelOrderByOrderIdSyncReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): CancelOrderByOrderIdSyncReq {
        return this.obj;
    }
}
