// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class CancelAllOrdersBySymbolReq implements Serializable<CancelAllOrdersBySymbolReq> {
    /**
     * symbol
     */
    symbol?: string;

    /**
     * Creates a new instance of the `CancelAllOrdersBySymbolReq` class.
     * The builder pattern allows step-by-step construction of a `CancelAllOrdersBySymbolReq` object.
     */
    static builder(): CancelAllOrdersBySymbolReqBuilder {
        return new CancelAllOrdersBySymbolReqBuilder();
    }

    /**
     * Creates a new instance of the `CancelAllOrdersBySymbolReq` class with the given data.
     */
    static create(data: {
        /**
         * symbol
         */
        symbol?: string;
    }): CancelAllOrdersBySymbolReq {
        let obj = new CancelAllOrdersBySymbolReq();
        obj.symbol = data.symbol;
        return obj;
    }

    fromJson(input: string): CancelAllOrdersBySymbolReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(CancelAllOrdersBySymbolReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): CancelAllOrdersBySymbolReq {
        return plainToInstance(CancelAllOrdersBySymbolReq, jsonObject);
    }
}

export class CancelAllOrdersBySymbolReqBuilder {
    obj: CancelAllOrdersBySymbolReq = new CancelAllOrdersBySymbolReq();
    /**
     * symbol
     */
    setSymbol(value: string): CancelAllOrdersBySymbolReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): CancelAllOrdersBySymbolReq {
        return this.obj;
    }
}
