// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class BatchCancelStopOrderResp implements Response<RestResponse> {
    /**
     * order id array
     */
    cancelledOrderIds: Array<string>;

    private constructor() {
        // @ts-ignore
        this.cancelledOrderIds = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): BatchCancelStopOrderResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): BatchCancelStopOrderResp {
        return plainToClassFromExist(new BatchCancelStopOrderResp(), jsonObject);
    }
}
