// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetOcoOrderListItems implements Serializable<GetOcoOrderListItems> {
    /**
     * The unique order id generated by the trading system,which can be used later for further actions such as canceling the order.
     */
    orderId?: string;
    /**
     * symbol
     */
    symbol?: string;
    /**
     * Client Order Id
     */
    clientOid?: string;
    /**
     * Order placement time, milliseconds
     */
    orderTime?: number;
    /**
     * Order status: NEW: New, DONE: Completed, TRIGGERED: Triggered, CANCELLED: Cancelled
     */
    status?: GetOcoOrderListItems.StatusEnum;
    fromJson(input: string): GetOcoOrderListItems {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetOcoOrderListItems, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetOcoOrderListItems {
        return plainToInstance(GetOcoOrderListItems, jsonObject);
    }
}

export namespace GetOcoOrderListItems {
    export enum StatusEnum {
        /**
         * New
         */
        NEW = <any>'NEW',
        /**
         * Completed
         */
        DONE = <any>'DONE',
        /**
         * Triggered
         */
        TRIGGERED = <any>'TRIGGERED',
        /**
         * Cancelled
         */
        CANCELLED = <any>'CANCELLED',
    }
}
