// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { BatchAddOrdersOldData } from './model_batch_add_orders_old_data';
import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class BatchAddOrdersOldResp implements Response<RestResponse> {
    /**
     *
     */
    @Type(() => BatchAddOrdersOldData)
    data: Array<BatchAddOrdersOldData>;

    private constructor() {
        // @ts-ignore
        this.data = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): BatchAddOrdersOldResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): BatchAddOrdersOldResp {
        return plainToClassFromExist(new BatchAddOrdersOldResp(), jsonObject);
    }
}
