// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetStopOrdersListItems } from './model_get_stop_orders_list_items';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetStopOrdersListResp implements Response<GetStopOrdersListResp, RestResponse> {
    /**
     * current page id
     */
    currentPage?: number;
    /**
     *
     */
    pageSize?: number;
    /**
     * the stop order count
     */
    totalNum?: number;
    /**
     * total page count of the list
     */
    totalPage?: number;
    /**
     * the list of stop orders
     */
    @Type(() => GetStopOrdersListItems)
    items?: Array<GetStopOrdersListItems>;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetStopOrdersListResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetStopOrdersListResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetStopOrdersListResp {
        return plainToInstance(GetStopOrdersListResp, jsonObject);
    }
}
