// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class CancelOrderByOrderIdReq implements Serializable {
    /**
     * The unique order id generated by the trading system
     */
    @Reflect.metadata('path', 'orderId')
    orderId?: string;

    /**
     * symbol
     */
    symbol?: string;

    private constructor() {}
    /**
     * Creates a new instance of the `CancelOrderByOrderIdReq` class.
     * The builder pattern allows step-by-step construction of a `CancelOrderByOrderIdReq` object.
     */
    static builder(): CancelOrderByOrderIdReqBuilder {
        return new CancelOrderByOrderIdReqBuilder(new CancelOrderByOrderIdReq());
    }

    /**
     * Creates a new instance of the `CancelOrderByOrderIdReq` class with the given data.
     */
    static create(data: {
        /**
         * The unique order id generated by the trading system
         */
        orderId?: string;
        /**
         * symbol
         */
        symbol?: string;
    }): CancelOrderByOrderIdReq {
        let obj = new CancelOrderByOrderIdReq();
        obj.orderId = data.orderId;
        obj.symbol = data.symbol;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): CancelOrderByOrderIdReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): CancelOrderByOrderIdReq {
        return plainToClassFromExist(new CancelOrderByOrderIdReq(), jsonObject);
    }
}

export class CancelOrderByOrderIdReqBuilder {
    constructor(readonly obj: CancelOrderByOrderIdReq) {
        this.obj = obj;
    }
    /**
     * The unique order id generated by the trading system
     */
    setOrderId(value: string): CancelOrderByOrderIdReqBuilder {
        this.obj.orderId = value;
        return this;
    }

    /**
     * symbol
     */
    setSymbol(value: string): CancelOrderByOrderIdReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): CancelOrderByOrderIdReq {
        return this.obj;
    }
}
