// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetOpenOrdersReq implements Serializable<GetOpenOrdersReq> {
    /**
     * symbol
     */
    symbol?: string;
    /**
     * Order type: MARGIN_TRADE - cross margin trading order, MARGIN_ISOLATED_TRADE - isolated margin trading order
     */
    tradeType?: GetOpenOrdersReq.TradeTypeEnum;

    /**
     * Creates a new instance of the `GetOpenOrdersReq` class.
     * The builder pattern allows step-by-step construction of a `GetOpenOrdersReq` object.
     */
    static builder(): GetOpenOrdersReqBuilder {
        return new GetOpenOrdersReqBuilder();
    }

    /**
     * Creates a new instance of the `GetOpenOrdersReq` class with the given data.
     */
    static create(data: {
        /**
         * symbol
         */
        symbol?: string;
        /**
         * Order type: MARGIN_TRADE - cross margin trading order, MARGIN_ISOLATED_TRADE - isolated margin trading order
         */
        tradeType?: GetOpenOrdersReq.TradeTypeEnum;
    }): GetOpenOrdersReq {
        let obj = new GetOpenOrdersReq();
        obj.symbol = data.symbol;
        obj.tradeType = data.tradeType;
        return obj;
    }

    fromJson(input: string): GetOpenOrdersReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetOpenOrdersReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetOpenOrdersReq {
        return plainToInstance(GetOpenOrdersReq, jsonObject);
    }
}

export namespace GetOpenOrdersReq {
    export enum TradeTypeEnum {
        /**
         *
         */
        MARGIN_TRADE = <any>'MARGIN_TRADE',
        /**
         *
         */
        MARGIN_ISOLATED_TRADE = <any>'MARGIN_ISOLATED_TRADE',
    }
}

export class GetOpenOrdersReqBuilder {
    obj: GetOpenOrdersReq = new GetOpenOrdersReq();
    /**
     * symbol
     */
    setSymbol(value: string): GetOpenOrdersReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Order type: MARGIN_TRADE - cross margin trading order, MARGIN_ISOLATED_TRADE - isolated margin trading order
     */
    setTradeType(value: GetOpenOrdersReq.TradeTypeEnum): GetOpenOrdersReqBuilder {
        this.obj.tradeType = value;
        return this;
    }

    build(): GetOpenOrdersReq {
        return this.obj;
    }
}
