import * as ORDER from './order';
import * as MARKET from './market';
import * as SPOTPRIVATE from './spotprivate';
import * as SPOTPUBLIC from './spotpublic';
export const Spot = {
    Order: ORDER,
    Market: MARKET,
    SpotPrivate: SPOTPRIVATE,
    SpotPublic: SPOTPUBLIC,
};
export namespace Spot {
    export type OrderAPI = ORDER.OrderAPI;
    export type MarketAPI = MARKET.MarketAPI;
    export type SpotPrivateWS = SPOTPRIVATE.SpotPrivateWS;
    export type SpotPublicWS = SPOTPUBLIC.SpotPublicWS;
    export namespace Order {
        export type AddOcoOrderReq = ORDER.AddOcoOrderReq;
        export type AddOcoOrderResp = ORDER.AddOcoOrderResp;
        export type AddOrderOldReq = ORDER.AddOrderOldReq;
        export type AddOrderOldResp = ORDER.AddOrderOldResp;
        export type AddOrderReq = ORDER.AddOrderReq;
        export type AddOrderResp = ORDER.AddOrderResp;
        export type AddOrderSyncReq = ORDER.AddOrderSyncReq;
        export type AddOrderSyncResp = ORDER.AddOrderSyncResp;
        export type AddOrderTestOldReq = ORDER.AddOrderTestOldReq;
        export type AddOrderTestOldResp = ORDER.AddOrderTestOldResp;
        export type AddOrderTestReq = ORDER.AddOrderTestReq;
        export type AddOrderTestResp = ORDER.AddOrderTestResp;
        export type AddStopOrderReq = ORDER.AddStopOrderReq;
        export type AddStopOrderResp = ORDER.AddStopOrderResp;
        export type BatchAddOrdersData = ORDER.BatchAddOrdersData;
        export type BatchAddOrdersOldData = ORDER.BatchAddOrdersOldData;
        export type BatchAddOrdersOldOrderList = ORDER.BatchAddOrdersOldOrderList;
        export type BatchAddOrdersOldReq = ORDER.BatchAddOrdersOldReq;
        export type BatchAddOrdersOldResp = ORDER.BatchAddOrdersOldResp;
        export type BatchAddOrdersOrderList = ORDER.BatchAddOrdersOrderList;
        export type BatchAddOrdersReq = ORDER.BatchAddOrdersReq;
        export type BatchAddOrdersResp = ORDER.BatchAddOrdersResp;
        export type BatchAddOrdersSyncData = ORDER.BatchAddOrdersSyncData;
        export type BatchAddOrdersSyncOrderList = ORDER.BatchAddOrdersSyncOrderList;
        export type BatchAddOrdersSyncReq = ORDER.BatchAddOrdersSyncReq;
        export type BatchAddOrdersSyncResp = ORDER.BatchAddOrdersSyncResp;
        export type BatchCancelOcoOrdersReq = ORDER.BatchCancelOcoOrdersReq;
        export type BatchCancelOcoOrdersResp = ORDER.BatchCancelOcoOrdersResp;
        export type BatchCancelOrderOldReq = ORDER.BatchCancelOrderOldReq;
        export type BatchCancelOrderOldResp = ORDER.BatchCancelOrderOldResp;
        export type BatchCancelStopOrderReq = ORDER.BatchCancelStopOrderReq;
        export type BatchCancelStopOrderResp = ORDER.BatchCancelStopOrderResp;
        export type CancelAllOrdersBySymbolReq = ORDER.CancelAllOrdersBySymbolReq;
        export type CancelAllOrdersBySymbolResp = ORDER.CancelAllOrdersBySymbolResp;
        export type CancelAllOrdersFailedSymbols = ORDER.CancelAllOrdersFailedSymbols;
        export type CancelAllOrdersResp = ORDER.CancelAllOrdersResp;
        export type CancelOcoOrderByClientOidReq = ORDER.CancelOcoOrderByClientOidReq;
        export type CancelOcoOrderByClientOidResp = ORDER.CancelOcoOrderByClientOidResp;
        export type CancelOcoOrderByOrderIdReq = ORDER.CancelOcoOrderByOrderIdReq;
        export type CancelOcoOrderByOrderIdResp = ORDER.CancelOcoOrderByOrderIdResp;
        export type CancelOrderByClientOidOldReq = ORDER.CancelOrderByClientOidOldReq;
        export type CancelOrderByClientOidOldResp = ORDER.CancelOrderByClientOidOldResp;
        export type CancelOrderByClientOidReq = ORDER.CancelOrderByClientOidReq;
        export type CancelOrderByClientOidResp = ORDER.CancelOrderByClientOidResp;
        export type CancelOrderByClientOidSyncReq = ORDER.CancelOrderByClientOidSyncReq;
        export type CancelOrderByClientOidSyncResp = ORDER.CancelOrderByClientOidSyncResp;
        export type CancelOrderByOrderIdOldReq = ORDER.CancelOrderByOrderIdOldReq;
        export type CancelOrderByOrderIdOldResp = ORDER.CancelOrderByOrderIdOldResp;
        export type CancelOrderByOrderIdReq = ORDER.CancelOrderByOrderIdReq;
        export type CancelOrderByOrderIdResp = ORDER.CancelOrderByOrderIdResp;
        export type CancelOrderByOrderIdSyncReq = ORDER.CancelOrderByOrderIdSyncReq;
        export type CancelOrderByOrderIdSyncResp = ORDER.CancelOrderByOrderIdSyncResp;
        export type CancelPartialOrderReq = ORDER.CancelPartialOrderReq;
        export type CancelPartialOrderResp = ORDER.CancelPartialOrderResp;
        export type CancelStopOrderByClientOidReq = ORDER.CancelStopOrderByClientOidReq;
        export type CancelStopOrderByClientOidResp = ORDER.CancelStopOrderByClientOidResp;
        export type CancelStopOrderByOrderIdReq = ORDER.CancelStopOrderByOrderIdReq;
        export type CancelStopOrderByOrderIdResp = ORDER.CancelStopOrderByOrderIdResp;
        export type GetClosedOrdersItems = ORDER.GetClosedOrdersItems;
        export type GetClosedOrdersReq = ORDER.GetClosedOrdersReq;
        export type GetClosedOrdersResp = ORDER.GetClosedOrdersResp;
        export type GetDCPResp = ORDER.GetDCPResp;
        export type GetOcoOrderByClientOidReq = ORDER.GetOcoOrderByClientOidReq;
        export type GetOcoOrderByClientOidResp = ORDER.GetOcoOrderByClientOidResp;
        export type GetOcoOrderByOrderIdReq = ORDER.GetOcoOrderByOrderIdReq;
        export type GetOcoOrderByOrderIdResp = ORDER.GetOcoOrderByOrderIdResp;
        export type GetOcoOrderDetailByOrderIdOrders = ORDER.GetOcoOrderDetailByOrderIdOrders;
        export type GetOcoOrderDetailByOrderIdReq = ORDER.GetOcoOrderDetailByOrderIdReq;
        export type GetOcoOrderDetailByOrderIdResp = ORDER.GetOcoOrderDetailByOrderIdResp;
        export type GetOcoOrderListItems = ORDER.GetOcoOrderListItems;
        export type GetOcoOrderListReq = ORDER.GetOcoOrderListReq;
        export type GetOcoOrderListResp = ORDER.GetOcoOrderListResp;
        export type GetOpenOrdersData = ORDER.GetOpenOrdersData;
        export type GetOpenOrdersReq = ORDER.GetOpenOrdersReq;
        export type GetOpenOrdersResp = ORDER.GetOpenOrdersResp;
        export type GetOrderByClientOidOldReq = ORDER.GetOrderByClientOidOldReq;
        export type GetOrderByClientOidOldResp = ORDER.GetOrderByClientOidOldResp;
        export type GetOrderByClientOidReq = ORDER.GetOrderByClientOidReq;
        export type GetOrderByClientOidResp = ORDER.GetOrderByClientOidResp;
        export type GetOrderByOrderIdOldReq = ORDER.GetOrderByOrderIdOldReq;
        export type GetOrderByOrderIdOldResp = ORDER.GetOrderByOrderIdOldResp;
        export type GetOrderByOrderIdReq = ORDER.GetOrderByOrderIdReq;
        export type GetOrderByOrderIdResp = ORDER.GetOrderByOrderIdResp;
        export type GetOrdersListOldItems = ORDER.GetOrdersListOldItems;
        export type GetOrdersListOldReq = ORDER.GetOrdersListOldReq;
        export type GetOrdersListOldResp = ORDER.GetOrdersListOldResp;
        export type GetRecentOrdersListOldData = ORDER.GetRecentOrdersListOldData;
        export type GetRecentOrdersListOldReq = ORDER.GetRecentOrdersListOldReq;
        export type GetRecentOrdersListOldResp = ORDER.GetRecentOrdersListOldResp;
        export type GetRecentTradeHistoryOldData = ORDER.GetRecentTradeHistoryOldData;
        export type GetRecentTradeHistoryOldReq = ORDER.GetRecentTradeHistoryOldReq;
        export type GetRecentTradeHistoryOldResp = ORDER.GetRecentTradeHistoryOldResp;
        export type GetStopOrderByClientOidData = ORDER.GetStopOrderByClientOidData;
        export type GetStopOrderByClientOidReq = ORDER.GetStopOrderByClientOidReq;
        export type GetStopOrderByClientOidResp = ORDER.GetStopOrderByClientOidResp;
        export type GetStopOrderByOrderIdReq = ORDER.GetStopOrderByOrderIdReq;
        export type GetStopOrderByOrderIdResp = ORDER.GetStopOrderByOrderIdResp;
        export type GetStopOrdersListItems = ORDER.GetStopOrdersListItems;
        export type GetStopOrdersListReq = ORDER.GetStopOrdersListReq;
        export type GetStopOrdersListResp = ORDER.GetStopOrdersListResp;
        export type GetSymbolsWithOpenOrderResp = ORDER.GetSymbolsWithOpenOrderResp;
        export type GetTradeHistoryItems = ORDER.GetTradeHistoryItems;
        export type GetTradeHistoryOldItems = ORDER.GetTradeHistoryOldItems;
        export type GetTradeHistoryOldReq = ORDER.GetTradeHistoryOldReq;
        export type GetTradeHistoryOldResp = ORDER.GetTradeHistoryOldResp;
        export type GetTradeHistoryReq = ORDER.GetTradeHistoryReq;
        export type GetTradeHistoryResp = ORDER.GetTradeHistoryResp;
        export type ModifyOrderReq = ORDER.ModifyOrderReq;
        export type ModifyOrderResp = ORDER.ModifyOrderResp;
        export type SetDCPReq = ORDER.SetDCPReq;
        export type SetDCPResp = ORDER.SetDCPResp;
    }
    export namespace SpotPrivate {
        export type AccountEvent = SPOTPRIVATE.AccountEvent;
        export type AccountRelationContext = SPOTPRIVATE.AccountRelationContext;
        export type OrderV1Event = SPOTPRIVATE.OrderV1Event;
        export type OrderV2Event = SPOTPRIVATE.OrderV2Event;
    }
    export namespace Market {
        export type Get24hrStatsReq = MARKET.Get24hrStatsReq;
        export type Get24hrStatsResp = MARKET.Get24hrStatsResp;
        export type GetAllCurrenciesData = MARKET.GetAllCurrenciesData;
        export type GetAllCurrenciesDataChains = MARKET.GetAllCurrenciesDataChains;
        export type GetAllCurrenciesResp = MARKET.GetAllCurrenciesResp;
        export type GetAllSymbolsData = MARKET.GetAllSymbolsData;
        export type GetAllSymbolsReq = MARKET.GetAllSymbolsReq;
        export type GetAllSymbolsResp = MARKET.GetAllSymbolsResp;
        export type GetAllTickersResp = MARKET.GetAllTickersResp;
        export type GetAllTickersTicker = MARKET.GetAllTickersTicker;
        export type GetAnnouncementsItems = MARKET.GetAnnouncementsItems;
        export type GetAnnouncementsReq = MARKET.GetAnnouncementsReq;
        export type GetAnnouncementsResp = MARKET.GetAnnouncementsResp;
        export type GetCurrencyChains = MARKET.GetCurrencyChains;
        export type GetCurrencyReq = MARKET.GetCurrencyReq;
        export type GetCurrencyResp = MARKET.GetCurrencyResp;
        export type GetFiatPriceReq = MARKET.GetFiatPriceReq;
        export type GetFiatPriceResp = MARKET.GetFiatPriceResp;
        export type GetFullOrderBookReq = MARKET.GetFullOrderBookReq;
        export type GetFullOrderBookResp = MARKET.GetFullOrderBookResp;
        export type GetKlinesReq = MARKET.GetKlinesReq;
        export type GetKlinesResp = MARKET.GetKlinesResp;
        export type GetMarketListResp = MARKET.GetMarketListResp;
        export type GetPartOrderBookReq = MARKET.GetPartOrderBookReq;
        export type GetPartOrderBookResp = MARKET.GetPartOrderBookResp;
        export type GetPrivateTokenInstanceServers = MARKET.GetPrivateTokenInstanceServers;
        export type GetPrivateTokenResp = MARKET.GetPrivateTokenResp;
        export type GetPublicTokenInstanceServers = MARKET.GetPublicTokenInstanceServers;
        export type GetPublicTokenResp = MARKET.GetPublicTokenResp;
        export type GetServerTimeResp = MARKET.GetServerTimeResp;
        export type GetServiceStatusResp = MARKET.GetServiceStatusResp;
        export type GetSymbolReq = MARKET.GetSymbolReq;
        export type GetSymbolResp = MARKET.GetSymbolResp;
        export type GetTickerReq = MARKET.GetTickerReq;
        export type GetTickerResp = MARKET.GetTickerResp;
        export type GetTradeHistoryData = MARKET.GetTradeHistoryData;
        export type GetTradeHistoryReq = MARKET.GetTradeHistoryReq;
        export type GetTradeHistoryResp = MARKET.GetTradeHistoryResp;
    }
    export namespace SpotPublic {
        export type AllTickersEvent = SPOTPUBLIC.AllTickersEvent;
        export type KlinesEvent = SPOTPUBLIC.KlinesEvent;
        export type MarketSnapshotData = SPOTPUBLIC.MarketSnapshotData;
        export type MarketSnapshotDataMarketChange1h = SPOTPUBLIC.MarketSnapshotDataMarketChange1h;
        export type MarketSnapshotDataMarketChange24h =
            SPOTPUBLIC.MarketSnapshotDataMarketChange24h;
        export type MarketSnapshotDataMarketChange4h = SPOTPUBLIC.MarketSnapshotDataMarketChange4h;
        export type MarketSnapshotEvent = SPOTPUBLIC.MarketSnapshotEvent;
        export type OrderbookIncrementChanges = SPOTPUBLIC.OrderbookIncrementChanges;
        export type OrderbookIncrementEvent = SPOTPUBLIC.OrderbookIncrementEvent;
        export type OrderbookLevel1Event = SPOTPUBLIC.OrderbookLevel1Event;
        export type OrderbookLevel50Changes = SPOTPUBLIC.OrderbookLevel50Changes;
        export type OrderbookLevel50Event = SPOTPUBLIC.OrderbookLevel50Event;
        export type OrderbookLevel5Event = SPOTPUBLIC.OrderbookLevel5Event;
        export type SymbolSnapshotData = SPOTPUBLIC.SymbolSnapshotData;
        export type SymbolSnapshotDataMarketChange1h = SPOTPUBLIC.SymbolSnapshotDataMarketChange1h;
        export type SymbolSnapshotDataMarketChange24h =
            SPOTPUBLIC.SymbolSnapshotDataMarketChange24h;
        export type SymbolSnapshotDataMarketChange4h = SPOTPUBLIC.SymbolSnapshotDataMarketChange4h;
        export type SymbolSnapshotEvent = SPOTPUBLIC.SymbolSnapshotEvent;
        export type TickerEvent = SPOTPUBLIC.TickerEvent;
        export type TradeEvent = SPOTPUBLIC.TradeEvent;
    }
}
