// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetDepositAddressV2Data implements Serializable<GetDepositAddressV2Data> {
    /**
     * Deposit address
     */
    address?: string;
    /**
     * Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to the KuCoin, you need to fill in memo(tag). If you do not fill memo (tag), your deposit may not be available, please be cautious.
     */
    memo?: string;
    /**
     * The chainName of currency
     */
    chain?: string;
    /**
     * The chainId of currency
     */
    chainId?: string;
    /**
     * Deposit account type: main (funding account), trade (spot trading account)
     */
    to?: GetDepositAddressV2Data.ToEnum;
    /**
     * currency
     */
    currency?: string;
    /**
     * The token contract address.
     */
    contractAddress?: string;
    fromJson(input: string): GetDepositAddressV2Data {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetDepositAddressV2Data, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetDepositAddressV2Data {
        return plainToInstance(GetDepositAddressV2Data, jsonObject);
    }
}

export namespace GetDepositAddressV2Data {
    export enum ToEnum {
        /**
         *
         */
        MAIN = <any>'MAIN',
        /**
         *
         */
        TRADE = <any>'TRADE',
    }
}
