// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetDepositHistoryOldItems implements Serializable<GetDepositHistoryOldItems> {
    /**
     * Currency
     */
    currency?: string;
    /**
     * Creation time of the database record
     */
    createAt?: number;
    /**
     * Deposit amount
     */
    amount?: string;
    /**
     * Wallet Txid
     */
    walletTxId?: string;
    /**
     * Internal deposit or not
     */
    isInner?: boolean;
    /**
     *
     */
    status?: GetDepositHistoryOldItems.StatusEnum;
    fromJson(input: string): GetDepositHistoryOldItems {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetDepositHistoryOldItems, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetDepositHistoryOldItems {
        return plainToInstance(GetDepositHistoryOldItems, jsonObject);
    }
}

export namespace GetDepositHistoryOldItems {
    export enum StatusEnum {
        /**
         *
         */
        PROCESSING = <any>'PROCESSING',
        /**
         *
         */
        SUCCESS = <any>'SUCCESS',
        /**
         *
         */
        FAILURE = <any>'FAILURE',
    }
}
