// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetDepositHistoryOldReq implements Serializable {
    /**
     * currency
     */
    currency?: string;

    /**
     * Status. Available value: PROCESSING, SUCCESS, and FAILURE
     */
    status?: GetDepositHistoryOldReq.StatusEnum;

    /**
     * Start time (milisecond)
     */
    startAt?: number;

    /**
     * End time (milisecond)
     */
    endAt?: number;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetDepositHistoryOldReq` class.
     * The builder pattern allows step-by-step construction of a `GetDepositHistoryOldReq` object.
     */
    static builder(): GetDepositHistoryOldReqBuilder {
        return new GetDepositHistoryOldReqBuilder(new GetDepositHistoryOldReq());
    }

    /**
     * Creates a new instance of the `GetDepositHistoryOldReq` class with the given data.
     */
    static create(data: {
        /**
         * currency
         */
        currency?: string;
        /**
         * Status. Available value: PROCESSING, SUCCESS, and FAILURE
         */
        status?: GetDepositHistoryOldReq.StatusEnum;
        /**
         * Start time (milisecond)
         */
        startAt?: number;
        /**
         * End time (milisecond)
         */
        endAt?: number;
    }): GetDepositHistoryOldReq {
        let obj = new GetDepositHistoryOldReq();
        obj.currency = data.currency;
        obj.status = data.status;
        obj.startAt = data.startAt;
        obj.endAt = data.endAt;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetDepositHistoryOldReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetDepositHistoryOldReq {
        return plainToClassFromExist(new GetDepositHistoryOldReq(), jsonObject);
    }
}

export namespace GetDepositHistoryOldReq {
    export enum StatusEnum {
        /**
         *
         */
        PROCESSING = <any>'PROCESSING',
        /**
         *
         */
        SUCCESS = <any>'SUCCESS',
        /**
         *
         */
        FAILURE = <any>'FAILURE',
    }
}

export class GetDepositHistoryOldReqBuilder {
    constructor(readonly obj: GetDepositHistoryOldReq) {
        this.obj = obj;
    }
    /**
     * currency
     */
    setCurrency(value: string): GetDepositHistoryOldReqBuilder {
        this.obj.currency = value;
        return this;
    }

    /**
     * Status. Available value: PROCESSING, SUCCESS, and FAILURE
     */
    setStatus(value: GetDepositHistoryOldReq.StatusEnum): GetDepositHistoryOldReqBuilder {
        this.obj.status = value;
        return this;
    }

    /**
     * Start time (milisecond)
     */
    setStartAt(value: number): GetDepositHistoryOldReqBuilder {
        this.obj.startAt = value;
        return this;
    }

    /**
     * End time (milisecond)
     */
    setEndAt(value: number): GetDepositHistoryOldReqBuilder {
        this.obj.endAt = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetDepositHistoryOldReq {
        return this.obj;
    }
}
