// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetBrokerInfoReq implements Serializable {
    /**
     * Start time, for example: 20230110
     */
    begin?: string;

    /**
     * End time, for example: 20230210 (query data with a maximum interval of 6 months)
     */
    end?: string;

    /**
     * Transaction type, 1: spot 2: futures
     */
    tradeType?: GetBrokerInfoReq.TradeTypeEnum;

    private constructor() {}
    /**
     * Creates a new instance of the `GetBrokerInfoReq` class.
     * The builder pattern allows step-by-step construction of a `GetBrokerInfoReq` object.
     */
    static builder(): GetBrokerInfoReqBuilder {
        return new GetBrokerInfoReqBuilder(new GetBrokerInfoReq());
    }

    /**
     * Creates a new instance of the `GetBrokerInfoReq` class with the given data.
     */
    static create(data: {
        /**
         * Start time, for example: 20230110
         */
        begin?: string;
        /**
         * End time, for example: 20230210 (query data with a maximum interval of 6 months)
         */
        end?: string;
        /**
         * Transaction type, 1: spot 2: futures
         */
        tradeType?: GetBrokerInfoReq.TradeTypeEnum;
    }): GetBrokerInfoReq {
        let obj = new GetBrokerInfoReq();
        obj.begin = data.begin;
        obj.end = data.end;
        obj.tradeType = data.tradeType;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetBrokerInfoReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetBrokerInfoReq {
        return plainToClassFromExist(new GetBrokerInfoReq(), jsonObject);
    }
}

export namespace GetBrokerInfoReq {
    export enum TradeTypeEnum {
        /**
         * spot
         */
        _1 = <any>'1',
        /**
         * futures
         */
        _2 = <any>'2',
    }
}

export class GetBrokerInfoReqBuilder {
    constructor(readonly obj: GetBrokerInfoReq) {
        this.obj = obj;
    }
    /**
     * Start time, for example: 20230110
     */
    setBegin(value: string): GetBrokerInfoReqBuilder {
        this.obj.begin = value;
        return this;
    }

    /**
     * End time, for example: 20230210 (query data with a maximum interval of 6 months)
     */
    setEnd(value: string): GetBrokerInfoReqBuilder {
        this.obj.end = value;
        return this;
    }

    /**
     * Transaction type, 1: spot 2: futures
     */
    setTradeType(value: GetBrokerInfoReq.TradeTypeEnum): GetBrokerInfoReqBuilder {
        this.obj.tradeType = value;
        return this;
    }

    build(): GetBrokerInfoReq {
        return this.obj;
    }
}
