// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetTransferHistoryResp implements Response<GetTransferHistoryResp, RestResponse> {
    /**
     * Transfer Order ID
     */
    orderId?: string;
    /**
     * Currency
     */
    currency?: string;
    /**
     * Transfer Amount
     */
    amount?: string;
    /**
     * UID of the user transferring out
     */
    fromUid?: number;
    /**
     * From Account Type:Account Type: MAIN, TRADE, CONTRACT, MARGIN, ISOLATED
     */
    fromAccountType?: GetTransferHistoryResp.FromAccountTypeEnum;
    /**
     * Trading pair, required if the account type is ISOLATED, e.g., BTC-USDT
     */
    fromAccountTag?: string;
    /**
     * UID of the user transferring in
     */
    toUid?: number;
    /**
     * Account Type:Account Type: MAIN, TRADE, CONTRACT, MARGIN, ISOLATED
     */
    toAccountType?: GetTransferHistoryResp.ToAccountTypeEnum;
    /**
     * To Trading pair, required if the account type is ISOLATED, e.g., BTC-USDT
     */
    toAccountTag?: string;
    /**
     * Status: PROCESSING (processing), SUCCESS (successful), FAILURE (failed)
     */
    status?: GetTransferHistoryResp.StatusEnum;
    /**
     * Failure Reason
     */
    reason?: string;
    /**
     * Creation Time (Unix timestamp in milliseconds)
     */
    createdAt?: number;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetTransferHistoryResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetTransferHistoryResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetTransferHistoryResp {
        return plainToInstance(GetTransferHistoryResp, jsonObject);
    }
}

export namespace GetTransferHistoryResp {
    export enum FromAccountTypeEnum {
        /**
         *
         */
        MAIN = <any>'MAIN',
        /**
         *
         */
        TRADE = <any>'TRADE',
        /**
         *
         */
        CONTRACT = <any>'CONTRACT',
        /**
         *
         */
        MARGIN = <any>'MARGIN',
        /**
         *
         */
        ISOLATED = <any>'ISOLATED',
    }
    export enum ToAccountTypeEnum {
        /**
         *
         */
        MAIN = <any>'MAIN',
        /**
         *
         */
        TRADE = <any>'TRADE',
        /**
         *
         */
        CONTRACT = <any>'CONTRACT',
        /**
         *
         */
        MARGIN = <any>'MARGIN',
        /**
         *
         */
        ISOLATED = <any>'ISOLATED',
    }
    export enum StatusEnum {
        /**
         *
         */
        PROCESSING = <any>'PROCESSING',
        /**
         *
         */
        SUCCESS = <any>'SUCCESS',
        /**
         *
         */
        FAILURE = <any>'FAILURE',
    }
}
