// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class TransferResp implements Response<TransferResp, RestResponse> {
    /**
     *
     */
    orderId?: string;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): TransferResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(TransferResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): TransferResp {
        return plainToInstance(TransferResp, jsonObject);
    }
}
