// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetWithdrawDetailReq implements Serializable<GetWithdrawDetailReq> {
    /**
     * Withdrawal ID
     */
    withdrawalId?: string;

    /**
     * Creates a new instance of the `GetWithdrawDetailReq` class.
     * The builder pattern allows step-by-step construction of a `GetWithdrawDetailReq` object.
     */
    static builder(): GetWithdrawDetailReqBuilder {
        return new GetWithdrawDetailReqBuilder();
    }

    /**
     * Creates a new instance of the `GetWithdrawDetailReq` class with the given data.
     */
    static create(data: {
        /**
         * Withdrawal ID
         */
        withdrawalId?: string;
    }): GetWithdrawDetailReq {
        let obj = new GetWithdrawDetailReq();
        obj.withdrawalId = data.withdrawalId;
        return obj;
    }

    fromJson(input: string): GetWithdrawDetailReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetWithdrawDetailReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetWithdrawDetailReq {
        return plainToInstance(GetWithdrawDetailReq, jsonObject);
    }
}

export class GetWithdrawDetailReqBuilder {
    obj: GetWithdrawDetailReq = new GetWithdrawDetailReq();
    /**
     * Withdrawal ID
     */
    setWithdrawalId(value: string): GetWithdrawDetailReqBuilder {
        this.obj.withdrawalId = value;
        return this;
    }

    build(): GetWithdrawDetailReq {
        return this.obj;
    }
}
