// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class ModifySubAccountApiReq implements Serializable<ModifySubAccountApiReq> {
    /**
     * Subaccount UID
     */
    uid?: string;
    /**
     * IP whitelist list, supports up to 20 IPs
     */
    ipWhitelist?: Array<string>;
    /**
     * [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list(Only General、Spot、Futures permissions can be set, such as \"General, Trade\". )
     */
    permissions?: Array<ModifySubAccountApiReq.PermissionsEnum>;
    /**
     * apikey remarks (length 4~32)
     */
    label?: string;
    /**
     * Subaccount apiKey
     */
    apiKey?: string;

    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class.
     * The builder pattern allows step-by-step construction of a `ModifySubAccountApiReq` object.
     */
    static builder(): ModifySubAccountApiReqBuilder {
        return new ModifySubAccountApiReqBuilder();
    }

    /**
     * Creates a new instance of the `ModifySubAccountApiReq` class with the given data.
     */
    static create(data: {
        /**
         * Subaccount UID
         */
        uid?: string;
        /**
         * IP whitelist list, supports up to 20 IPs
         */
        ipWhitelist?: Array<string>;
        /**
         * [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list(Only General、Spot、Futures permissions can be set, such as \"General, Trade\". )
         */
        permissions?: Array<ModifySubAccountApiReq.PermissionsEnum>;
        /**
         * apikey remarks (length 4~32)
         */
        label?: string;
        /**
         * Subaccount apiKey
         */
        apiKey?: string;
    }): ModifySubAccountApiReq {
        let obj = new ModifySubAccountApiReq();
        obj.uid = data.uid;
        obj.ipWhitelist = data.ipWhitelist;
        obj.permissions = data.permissions;
        obj.label = data.label;
        obj.apiKey = data.apiKey;
        return obj;
    }

    fromJson(input: string): ModifySubAccountApiReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(ModifySubAccountApiReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): ModifySubAccountApiReq {
        return plainToInstance(ModifySubAccountApiReq, jsonObject);
    }
}

export namespace ModifySubAccountApiReq {
    export enum PermissionsEnum {
        /**
         *
         */
        GENERAL = <any>'general',
        /**
         *
         */
        SPOT = <any>'spot',
        /**
         *
         */
        FUTURES = <any>'futures',
    }
}

export class ModifySubAccountApiReqBuilder {
    obj: ModifySubAccountApiReq = new ModifySubAccountApiReq();
    /**
     * Subaccount UID
     */
    setUid(value: string): ModifySubAccountApiReqBuilder {
        this.obj.uid = value;
        return this;
    }

    /**
     * IP whitelist list, supports up to 20 IPs
     */
    setIpWhitelist(value: Array<string>): ModifySubAccountApiReqBuilder {
        this.obj.ipWhitelist = value;
        return this;
    }

    /**
     * [Permissions](https://www.kucoin.com/docs-new/doc-338144) group list(Only General、Spot、Futures permissions can be set, such as \"General, Trade\". )
     */
    setPermissions(
        value: Array<ModifySubAccountApiReq.PermissionsEnum>,
    ): ModifySubAccountApiReqBuilder {
        this.obj.permissions = value;
        return this;
    }

    /**
     * apikey remarks (length 4~32)
     */
    setLabel(value: string): ModifySubAccountApiReqBuilder {
        this.obj.label = value;
        return this;
    }

    /**
     * Subaccount apiKey
     */
    setApiKey(value: string): ModifySubAccountApiReqBuilder {
        this.obj.apiKey = value;
        return this;
    }

    build(): ModifySubAccountApiReq {
        return this.obj;
    }
}
