// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetSubAccountItems implements Serializable {
    /**
     * Sub-account name
     */
    accountName: string;

    /**
     * Sub-account UID
     */
    uid: string;

    /**
     * Creation time, unix timestamp (milliseconds)
     */
    createdAt: number;

    /**
     * Sub-account VIP level
     */
    level: number;

    private constructor() {
        // @ts-ignore
        this.accountName = null;
        // @ts-ignore
        this.uid = null;
        // @ts-ignore
        this.createdAt = null;
        // @ts-ignore
        this.level = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetSubAccountItems {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetSubAccountItems {
        return plainToClassFromExist(new GetSubAccountItems(), jsonObject);
    }
}
