// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetStakingProductsReq implements Serializable<GetStakingProductsReq> {
    /**
     * currency
     */
    currency?: string;

    /**
     * Creates a new instance of the `GetStakingProductsReq` class.
     * The builder pattern allows step-by-step construction of a `GetStakingProductsReq` object.
     */
    static builder(): GetStakingProductsReqBuilder {
        return new GetStakingProductsReqBuilder();
    }

    /**
     * Creates a new instance of the `GetStakingProductsReq` class with the given data.
     */
    static create(data: {
        /**
         * currency
         */
        currency?: string;
    }): GetStakingProductsReq {
        let obj = new GetStakingProductsReq();
        obj.currency = data.currency;
        return obj;
    }

    fromJson(input: string): GetStakingProductsReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetStakingProductsReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetStakingProductsReq {
        return plainToInstance(GetStakingProductsReq, jsonObject);
    }
}

export class GetStakingProductsReqBuilder {
    obj: GetStakingProductsReq = new GetStakingProductsReq();
    /**
     * currency
     */
    setCurrency(value: string): GetStakingProductsReqBuilder {
        this.obj.currency = value;
        return this;
    }

    build(): GetStakingProductsReq {
        return this.obj;
    }
}
