// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class FlexTransferResp implements Response<RestResponse> {
    /**
     * Transfer order ID
     */
    orderId: string;

    private constructor() {
        // @ts-ignore
        this.orderId = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): FlexTransferResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): FlexTransferResp {
        return plainToClassFromExist(new FlexTransferResp(), jsonObject);
    }
}
