// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { GetFuturesAccountTransferOutLedgerItems } from './model_get_futures_account_transfer_out_ledger_items';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetFuturesAccountTransferOutLedgerResp implements Response<RestResponse> {
    /**
     * current page
     */
    currentPage: number;

    /**
     * page size
     */
    pageSize: number;

    /**
     * total number
     */
    totalNum: number;

    /**
     * total page
     */
    totalPage: number;

    /**
     *
     */
    @Type(() => GetFuturesAccountTransferOutLedgerItems)
    items: Array<GetFuturesAccountTransferOutLedgerItems>;

    private constructor() {
        // @ts-ignore
        this.currentPage = null;
        // @ts-ignore
        this.pageSize = null;
        // @ts-ignore
        this.totalNum = null;
        // @ts-ignore
        this.totalPage = null;
        // @ts-ignore
        this.items = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetFuturesAccountTransferOutLedgerResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetFuturesAccountTransferOutLedgerResp {
        return plainToClassFromExist(new GetFuturesAccountTransferOutLedgerResp(), jsonObject);
    }
}
