// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetTransferQuotasResp implements Response<GetTransferQuotasResp, RestResponse> {
    /**
     * Currency
     */
    currency?: string;
    /**
     * Total funds in an account.
     */
    balance?: string;
    /**
     * Funds available to withdraw or trade.
     */
    available?: string;
    /**
     * Funds on hold (not available for use).
     */
    holds?: string;
    /**
     * Funds available to transfer.
     */
    transferable?: string;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetTransferQuotasResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetTransferQuotasResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetTransferQuotasResp {
        return plainToInstance(GetTransferQuotasResp, jsonObject);
    }
}
