// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class FuturesAccountTransferOutResp implements Response<RestResponse> {
    /**
     * Transfer order ID
     */
    applyId: string;

    /**
     * Business number
     */
    bizNo: string;

    /**
     * Pay account type
     */
    payAccountType: string;

    /**
     * Pay account sub type
     */
    payTag: string;

    /**
     * User remark
     */
    remark: string;

    /**
     * Receive account type
     */
    recAccountType: string;

    /**
     * Receive account sub type
     */
    recTag: string;

    /**
     * Receive account tx remark
     */
    recRemark: string;

    /**
     * Receive system
     */
    recSystem: string;

    /**
     * Status:APPLY, PROCESSING, PENDING_APPROVAL, APPROVED, REJECTED, PENDING_CANCEL, CANCEL, SUCCESS
     */
    status: string;

    /**
     * Currency
     */
    currency: string;

    /**
     * Transfer amout
     */
    amount: string;

    /**
     * Transfer fee
     */
    fee: string;

    /**
     * Serial number
     */
    sn: number;

    /**
     * Fail Reason
     */
    reason: string;

    /**
     * Create time
     */
    createdAt: number;

    /**
     * Update time
     */
    updatedAt: number;

    private constructor() {
        // @ts-ignore
        this.applyId = null;
        // @ts-ignore
        this.bizNo = null;
        // @ts-ignore
        this.payAccountType = null;
        // @ts-ignore
        this.payTag = null;
        // @ts-ignore
        this.remark = null;
        // @ts-ignore
        this.recAccountType = null;
        // @ts-ignore
        this.recTag = null;
        // @ts-ignore
        this.recRemark = null;
        // @ts-ignore
        this.recSystem = null;
        // @ts-ignore
        this.status = null;
        // @ts-ignore
        this.currency = null;
        // @ts-ignore
        this.amount = null;
        // @ts-ignore
        this.fee = null;
        // @ts-ignore
        this.sn = null;
        // @ts-ignore
        this.reason = null;
        // @ts-ignore
        this.createdAt = null;
        // @ts-ignore
        this.updatedAt = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): FuturesAccountTransferOutResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): FuturesAccountTransferOutResp {
        return plainToClassFromExist(new FuturesAccountTransferOutResp(), jsonObject);
    }
}
