// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class FuturesAccountTransferInReq implements Serializable<FuturesAccountTransferInReq> {
    /**
     * Currency, including XBT,USDT...
     */
    currency?: string;
    /**
     * Amount to be transfered in
     */
    amount?: number;
    /**
     * Payment account type, including MAIN,TRADE
     */
    payAccountType?: FuturesAccountTransferInReq.PayAccountTypeEnum;

    /**
     * Creates a new instance of the `FuturesAccountTransferInReq` class.
     * The builder pattern allows step-by-step construction of a `FuturesAccountTransferInReq` object.
     */
    static builder(): FuturesAccountTransferInReqBuilder {
        return new FuturesAccountTransferInReqBuilder();
    }

    /**
     * Creates a new instance of the `FuturesAccountTransferInReq` class with the given data.
     */
    static create(data: {
        /**
         * Currency, including XBT,USDT...
         */
        currency?: string;
        /**
         * Amount to be transfered in
         */
        amount?: number;
        /**
         * Payment account type, including MAIN,TRADE
         */
        payAccountType?: FuturesAccountTransferInReq.PayAccountTypeEnum;
    }): FuturesAccountTransferInReq {
        let obj = new FuturesAccountTransferInReq();
        obj.currency = data.currency;
        obj.amount = data.amount;
        obj.payAccountType = data.payAccountType;
        return obj;
    }

    fromJson(input: string): FuturesAccountTransferInReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(FuturesAccountTransferInReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): FuturesAccountTransferInReq {
        return plainToInstance(FuturesAccountTransferInReq, jsonObject);
    }
}

export namespace FuturesAccountTransferInReq {
    export enum PayAccountTypeEnum {
        /**
         *
         */
        MAIN = <any>'MAIN',
        /**
         *
         */
        TRADE = <any>'TRADE',
    }
}

export class FuturesAccountTransferInReqBuilder {
    obj: FuturesAccountTransferInReq = new FuturesAccountTransferInReq();
    /**
     * Currency, including XBT,USDT...
     */
    setCurrency(value: string): FuturesAccountTransferInReqBuilder {
        this.obj.currency = value;
        return this;
    }

    /**
     * Amount to be transfered in
     */
    setAmount(value: number): FuturesAccountTransferInReqBuilder {
        this.obj.amount = value;
        return this;
    }

    /**
     * Payment account type, including MAIN,TRADE
     */
    setPayAccountType(
        value: FuturesAccountTransferInReq.PayAccountTypeEnum,
    ): FuturesAccountTransferInReqBuilder {
        this.obj.payAccountType = value;
        return this;
    }

    build(): FuturesAccountTransferInReq {
        return this.obj;
    }
}
