// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetPartOrderBookResp implements Response<RestResponse> {
    /**
     * Timestamp(millisecond)
     */
    time: number;

    /**
     * Sequence number
     */
    sequence: string;

    /**
     * bids, from high to low
     */
    bids: Array<Array<string>>;

    /**
     * asks, from low to high
     */
    asks: Array<Array<string>>;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {
        // @ts-ignore
        this.time = null;
        // @ts-ignore
        this.sequence = null;
        // @ts-ignore
        this.bids = null;
        // @ts-ignore
        this.asks = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetPartOrderBookResp {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetPartOrderBookResp {
        return plainToClassFromExist(new GetPartOrderBookResp(), jsonObject);
    }
}
