// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { GetAllCurrenciesDataChains } from './model_get_all_currencies_data_chains';
import { Type, instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetAllCurrenciesData implements Serializable {
    /**
     * A unique currency code that will never change
     */
    currency: string;

    /**
     * Currency name, will change after renaming
     */
    name: string;

    /**
     * Full name of a currency, will change after renaming
     */
    fullName: string;

    /**
     * Currency precision
     */
    precision: number;

    /**
     * Number of block confirmations
     */
    confirms: number;

    /**
     * Contract address
     */
    contractAddress: string;

    /**
     * Support margin or not
     */
    isMarginEnabled: boolean;

    /**
     * Support debit or not
     */
    isDebitEnabled: boolean;

    /**
     * chain list
     */
    @Type(() => GetAllCurrenciesDataChains)
    chains: Array<GetAllCurrenciesDataChains>;

    private constructor() {
        // @ts-ignore
        this.currency = null;
        // @ts-ignore
        this.name = null;
        // @ts-ignore
        this.fullName = null;
        // @ts-ignore
        this.precision = null;
        // @ts-ignore
        this.confirms = null;
        // @ts-ignore
        this.contractAddress = null;
        // @ts-ignore
        this.isMarginEnabled = null;
        // @ts-ignore
        this.isDebitEnabled = null;
        // @ts-ignore
        this.chains = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetAllCurrenciesData {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetAllCurrenciesData {
        return plainToClassFromExist(new GetAllCurrenciesData(), jsonObject);
    }
}
