// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class Get24hrStatsReq implements Serializable {
    /**
     * symbol
     */
    symbol?: string;

    private constructor() {}
    /**
     * Creates a new instance of the `Get24hrStatsReq` class.
     * The builder pattern allows step-by-step construction of a `Get24hrStatsReq` object.
     */
    static builder(): Get24hrStatsReqBuilder {
        return new Get24hrStatsReqBuilder(new Get24hrStatsReq());
    }

    /**
     * Creates a new instance of the `Get24hrStatsReq` class with the given data.
     */
    static create(data: {
        /**
         * symbol
         */
        symbol?: string;
    }): Get24hrStatsReq {
        let obj = new Get24hrStatsReq();
        obj.symbol = data.symbol;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): Get24hrStatsReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): Get24hrStatsReq {
        return plainToClassFromExist(new Get24hrStatsReq(), jsonObject);
    }
}

export class Get24hrStatsReqBuilder {
    constructor(readonly obj: Get24hrStatsReq) {
        this.obj = obj;
    }
    /**
     * symbol
     */
    setSymbol(value: string): Get24hrStatsReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): Get24hrStatsReq {
        return this.obj;
    }
}
