// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';

import { FeeAPI, FeeAPIImpl } from '@generate/account/fee/api_fee';
import { TransferAPI, TransferAPIImpl } from '@generate/account/transfer/api_transfer';
import { AccountAPI, AccountAPIImpl } from '@generate/account/account/api_account';
import { SubAccountAPIImpl, SubAccountAPI } from '@generate/account/subaccount/api_sub_account';
import { WithdrawalAPIImpl, WithdrawalAPI } from '@generate/account/withdrawal/api_withdrawal';
import { DepositAPIImpl, DepositAPI } from '@generate/account/deposit/api_deposit';

export interface AccountService {
    getAccountApi(): AccountAPI;

    getDepositApi(): DepositAPI;

    getWithdrawalApi(): WithdrawalAPI;

    getFeeApi(): FeeAPI;

    getSubAccountApi(): SubAccountAPI;

    getTransferApi(): TransferAPI;
}

export class AccountServiceImpl implements AccountService {
    private readonly transport: Transport;
    private readonly Account: AccountAPI;
    private readonly Deposit: DepositAPI;
    private readonly Withdrawal: WithdrawalAPI;
    private readonly Fee: FeeAPI;
    private readonly SubAccount: SubAccountAPI;
    private readonly Transfer: TransferAPI;

    constructor(transport: Transport) {
        this.transport = transport;
        this.Account = new AccountAPIImpl(transport);
        this.Deposit = new DepositAPIImpl(transport);
        this.Withdrawal = new WithdrawalAPIImpl(transport);
        this.Fee = new FeeAPIImpl(transport);
        this.SubAccount = new SubAccountAPIImpl(transport);
        this.Transfer = new TransferAPIImpl(transport);
    }

    getAccountApi(): AccountAPI {
        return this.Account;
    }

    getDepositApi(): DepositAPI {
        return this.Deposit;
    }

    getWithdrawalApi(): WithdrawalAPI {
        return this.Withdrawal;
    }

    getFeeApi(): FeeAPI {
        return this.Fee;
    }

    getSubAccountApi(): SubAccountAPI {
        return this.SubAccount;
    }

    getTransferApi(): TransferAPI {
        return this.Transfer;
    }
}
