// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';

import { AffiliateAPIImpl, AffiliateAPI } from '@generate/affiliate/affiliate/api_affiliate';

export interface AffiliateService {
    getAffiliateApi(): AffiliateAPI;
}

export class AffiliateServiceImpl implements AffiliateService {
    private readonly transport: Transport;
    private readonly affiliate: AffiliateAPI;

    constructor(transport: Transport) {
        this.transport = transport;
        this.affiliate = new AffiliateAPIImpl(transport);
    }

    getAffiliateApi(): AffiliateAPI {
        return this.affiliate;
    }
}
