// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';

import { MarketAPIImpl, MarketAPI } from '@generate/futures/market/api_market';
import { PositionsAPI, PositionsAPIImpl } from '@generate/futures/positions/api_positions';
import { OrderAPIImpl, OrderAPI } from '@generate/futures/order/api_order';
import { FundingFeesAPIImpl, FundingFeesAPI } from '@generate/futures/fundingfees/api_funding_fees';

export interface FuturesService {
    getOrderApi(): OrderAPI;

    getPositionsApi(): PositionsAPI;

    getFundingFeesApi(): FundingFeesAPI;

    getMarketApi(): MarketAPI;
}

export class FuturesServiceImpl implements FuturesService {
    private readonly transport: Transport;
    private readonly order: OrderAPI;
    private readonly positions: PositionsAPI;
    private readonly fundingFees: FundingFeesAPI;
    private readonly market: MarketAPI;

    constructor(transport: Transport) {
        this.transport = transport;
        this.order = new OrderAPIImpl(transport);
        this.positions = new PositionsAPIImpl(transport);
        this.fundingFees = new FundingFeesAPIImpl(transport);
        this.market = new MarketAPIImpl(transport);
    }

    getOrderApi(): OrderAPI {
        return this.order;
    }

    getPositionsApi(): PositionsAPI {
        return this.positions;
    }

    getFundingFeesApi(): FundingFeesAPI {
        return this.fundingFees;
    }

    getMarketApi(): MarketAPI {
        return this.market;
    }
}
