// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';

import { MarketAPIImpl, MarketAPI } from '@generate/futures/market/api_market';
import { PositionsAPI, PositionsAPIImpl } from '@generate/futures/positions/api_positions';
import { OrderAPIImpl, OrderAPI } from '@generate/futures/order/api_order';
import { FundingFeesAPIImpl, FundingFeesAPI } from '@generate/futures/fundingfees/api_funding_fees';

export interface FuturesService {
    getOrderApi(): OrderAPI;

    getPositionsApi(): PositionsAPI;

    getFundingFeesApi(): FundingFeesAPI;

    getMarketApi(): MarketAPI;
}

export class FuturesServiceImpl implements FuturesService {
    private readonly transport: Transport;
    private readonly Order: OrderAPI;
    private readonly Positions: PositionsAPI;
    private readonly FundingFees: FundingFeesAPI;
    private readonly Market: MarketAPI;

    constructor(transport: Transport) {
        this.transport = transport;
        this.Order = new OrderAPIImpl(transport);
        this.Positions = new PositionsAPIImpl(transport);
        this.FundingFees = new FundingFeesAPIImpl(transport);
        this.Market = new MarketAPIImpl(transport);
    }

    getOrderApi(): OrderAPI {
        return this.Order;
    }

    getPositionsApi(): PositionsAPI {
        return this.Positions;
    }

    getFundingFeesApi(): FundingFeesAPI {
        return this.FundingFees;
    }

    getMarketApi(): MarketAPI {
        return this.Market;
    }
}
