// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class CrossMarginPositionAssetListValue implements Serializable {
    /**
     *
     */
    total?: string;
    /**
     *
     */
    available?: string;
    /**
     *
     */
    hold?: string;

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): CrossMarginPositionAssetListValue {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): CrossMarginPositionAssetListValue {
        return plainToClassFromExist(new CrossMarginPositionAssetListValue(), jsonObject);
    }
}
