// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetInterestHistoryItems implements Serializable {
    /**
     * currency
     */
    currency: string;

    /**
     * Daily interest rate
     */
    dayRatio: string;

    /**
     * Interest amount
     */
    interestAmount: string;

    /**
     * Interest Timestamp
     */
    createdTime: number;

    private constructor() {
        // @ts-ignore
        this.currency = null;
        // @ts-ignore
        this.dayRatio = null;
        // @ts-ignore
        this.interestAmount = null;
        // @ts-ignore
        this.createdTime = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetInterestHistoryItems {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetInterestHistoryItems {
        return plainToClassFromExist(new GetInterestHistoryItems(), jsonObject);
    }
}
