// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetPublicFundingHistoryData implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol: string;

    /**
     * Funding rate
     */
    fundingRate: number;

    /**
     * Time point (milisecond)
     */
    timepoint: number;

    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.fundingRate = null;
        // @ts-ignore
        this.timepoint = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetPublicFundingHistoryData {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetPublicFundingHistoryData {
        return plainToClassFromExist(new GetPublicFundingHistoryData(), jsonObject);
    }
}
