// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetPrivateFundingHistoryDataList } from './model_get_private_funding_history_data_list';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetPrivateFundingHistoryResp
    implements Response<GetPrivateFundingHistoryResp, RestResponse>
{
    /**
     *
     */
    @Type(() => GetPrivateFundingHistoryDataList)
    dataList?: Array<GetPrivateFundingHistoryDataList>;
    /**
     * Whether there are more pages
     */
    hasMore?: boolean;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetPrivateFundingHistoryResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetPrivateFundingHistoryResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetPrivateFundingHistoryResp {
        return plainToInstance(GetPrivateFundingHistoryResp, jsonObject);
    }
}
