// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetCurrentFundingRateResp implements Response<RestResponse> {
    /**
     * Funding Rate Symbol
     */
    symbol: string;

    /**
     * Granularity (milisecond)
     */
    granularity: number;

    /**
     * The funding rate settlement time point of the previous cycle (milisecond)
     */
    timePoint: number;

    /**
     * Current cycle funding rate
     */
    value: number;

    /**
     * Predicted funding rate
     */
    predictedValue: number;

    /**
     * Maximum Funding Rate
     */
    fundingRateCap: number;

    /**
     * Minimum Funding Rate
     */
    fundingRateFloor: number;

    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.granularity = null;
        // @ts-ignore
        this.timePoint = null;
        // @ts-ignore
        this.value = null;
        // @ts-ignore
        this.predictedValue = null;
        // @ts-ignore
        this.fundingRateCap = null;
        // @ts-ignore
        this.fundingRateFloor = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetCurrentFundingRateResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetCurrentFundingRateResp {
        return plainToClassFromExist(new GetCurrentFundingRateResp(), jsonObject);
    }
}
