// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { GetPrivateFundingHistoryDataList } from './model_get_private_funding_history_data_list';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetPrivateFundingHistoryResp implements Response<RestResponse> {
    /**
     *
     */
    @Type(() => GetPrivateFundingHistoryDataList)
    dataList: Array<GetPrivateFundingHistoryDataList>;

    /**
     * Whether there are more pages
     */
    hasMore: boolean;

    private constructor() {
        // @ts-ignore
        this.dataList = null;
        // @ts-ignore
        this.hasMore = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetPrivateFundingHistoryResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetPrivateFundingHistoryResp {
        return plainToClassFromExist(new GetPrivateFundingHistoryResp(), jsonObject);
    }
}
