// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class ModifyAutoDepositStatusReq implements Serializable<ModifyAutoDepositStatusReq> {
    /**
     * Symbol of the contract
     */
    symbol?: string;
    /**
     * Status
     */
    status?: boolean;

    /**
     * Creates a new instance of the `ModifyAutoDepositStatusReq` class.
     * The builder pattern allows step-by-step construction of a `ModifyAutoDepositStatusReq` object.
     */
    static builder(): ModifyAutoDepositStatusReqBuilder {
        return new ModifyAutoDepositStatusReqBuilder();
    }

    /**
     * Creates a new instance of the `ModifyAutoDepositStatusReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract
         */
        symbol?: string;
        /**
         * Status
         */
        status?: boolean;
    }): ModifyAutoDepositStatusReq {
        let obj = new ModifyAutoDepositStatusReq();
        obj.symbol = data.symbol;
        obj.status = data.status;
        return obj;
    }

    fromJson(input: string): ModifyAutoDepositStatusReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(ModifyAutoDepositStatusReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): ModifyAutoDepositStatusReq {
        return plainToInstance(ModifyAutoDepositStatusReq, jsonObject);
    }
}

export class ModifyAutoDepositStatusReqBuilder {
    obj: ModifyAutoDepositStatusReq = new ModifyAutoDepositStatusReq();
    /**
     * Symbol of the contract
     */
    setSymbol(value: string): ModifyAutoDepositStatusReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Status
     */
    setStatus(value: boolean): ModifyAutoDepositStatusReqBuilder {
        this.obj.status = value;
        return this;
    }

    build(): ModifyAutoDepositStatusReq {
        return this.obj;
    }
}
