// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class AddIsolatedMarginResp implements Response<AddIsolatedMarginResp, RestResponse> {
    /**
     * Position ID
     */
    id?: string;
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;
    /**
     * Auto deposit margin or not
     */
    autoDeposit?: boolean;
    /**
     * Maintenance margin requirement
     */
    maintMarginReq?: string;
    /**
     * Risk limit
     */
    riskLimit?: number;
    /**
     * Leverage o the order
     */
    realLeverage?: string;
    /**
     * Cross mode or not
     */
    crossMode?: boolean;
    /**
     * ADL ranking percentile
     */
    delevPercentage?: number;
    /**
     * Open time
     */
    openingTimestamp?: number;
    /**
     * Current timestamp
     */
    currentTimestamp?: number;
    /**
     * Current postion quantity
     */
    currentQty?: number;
    /**
     * Current postion value
     */
    currentCost?: string;
    /**
     * Current commission
     */
    currentComm?: string;
    /**
     * Unrealised value
     */
    unrealisedCost?: string;
    /**
     * Accumulated realised gross profit value
     */
    realisedGrossCost?: string;
    /**
     * Current realised position value
     */
    realisedCost?: string;
    /**
     * Opened position or not
     */
    isOpen?: boolean;
    /**
     * Mark price
     */
    markPrice?: string;
    /**
     * Mark value
     */
    markValue?: string;
    /**
     * Position value
     */
    posCost?: string;
    /**
     * added margin
     */
    posCross?: string;
    /**
     * Leverage margin
     */
    posInit?: string;
    /**
     * Bankruptcy cost
     */
    posComm?: string;
    /**
     * Funding fees paid out
     */
    posLoss?: string;
    /**
     * Position margin
     */
    posMargin?: string;
    /**
     * Maintenance margin
     */
    posMaint?: string;
    /**
     * Position margin
     */
    maintMargin?: string;
    /**
     * Accumulated realised gross profit value
     */
    realisedGrossPnl?: string;
    /**
     * Realised profit and loss
     */
    realisedPnl?: string;
    /**
     * Unrealised profit and loss
     */
    unrealisedPnl?: string;
    /**
     * Profit-loss ratio of the position
     */
    unrealisedPnlPcnt?: string;
    /**
     * Rate of return on investment
     */
    unrealisedRoePcnt?: string;
    /**
     * Average entry price
     */
    avgEntryPrice?: string;
    /**
     * Liquidation price
     */
    liquidationPrice?: string;
    /**
     * Bankruptcy price
     */
    bankruptPrice?: string;
    /**
     * Currency used to clear and settle the trades
     */
    settleCurrency?: string;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): AddIsolatedMarginResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(AddIsolatedMarginResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): AddIsolatedMarginResp {
        return plainToInstance(AddIsolatedMarginResp, jsonObject);
    }
}
