// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class CancelOrderByIdReq implements Serializable {
    /**
     * Order id
     */
    orderId?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `CancelOrderByIdReq` class.
     * The builder pattern allows step-by-step construction of a `CancelOrderByIdReq` object.
     */
    static builder(): CancelOrderByIdReqBuilder {
        return new CancelOrderByIdReqBuilder(new CancelOrderByIdReq());
    }

    /**
     * Creates a new instance of the `CancelOrderByIdReq` class with the given data.
     */
    static create(data: {
        /**
         * Order id
         */
        orderId?: string;
    }): CancelOrderByIdReq {
        let obj = new CancelOrderByIdReq();
        obj.orderId = data.orderId;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): CancelOrderByIdReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): CancelOrderByIdReq {
        return plainToClassFromExist(new CancelOrderByIdReq(), jsonObject);
    }
}

export class CancelOrderByIdReqBuilder {
    constructor(readonly obj: CancelOrderByIdReq) {
        this.obj = obj;
    }
    /**
     * Order id
     */
    setOrderId(value: string): CancelOrderByIdReqBuilder {
        this.obj.orderId = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): CancelOrderByIdReq {
        return this.obj;
    }
}
