// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Transport } from '@internal/interfaces/transport';
import { GetAccountDetailResp } from './model_get_account_detail_resp';
import { GetAccountsResp } from './model_get_accounts_resp';

export interface VIPLendingAPI {
    /**
     * getAccountDetail Get Account Detail
     * Description: The following information is only applicable to loans.  Get information on off-exchange funding and loans, This endpoint is only for querying accounts that are currently involved in loans.
     * Documentation: https://www.kucoin.com/docs-new/api-3470277
     * +---------------------+------------+
     * | Extra API Info      | Value      |
     * +---------------------+------------+
     * | API-DOMAIN          | SPOT       |
     * | API-CHANNEL         | PRIVATE    |
     * | API-PERMISSION      | GENERAL    |
     * | API-RATE-LIMIT-POOL | MANAGEMENT |
     * | API-RATE-LIMIT      | 1          |
     * +---------------------+------------+
     */
    getAccountDetail(): Promise<GetAccountDetailResp>;

    /**
     * getAccounts Get Accounts
     * Description: Accounts participating in OTC lending, This interface is only for querying accounts currently running OTC lending.
     * Documentation: https://www.kucoin.com/docs-new/api-3470278
     * +---------------------+------------+
     * | Extra API Info      | Value      |
     * +---------------------+------------+
     * | API-DOMAIN          | SPOT       |
     * | API-CHANNEL         | PRIVATE    |
     * | API-PERMISSION      | GENERAL    |
     * | API-RATE-LIMIT-POOL | MANAGEMENT |
     * | API-RATE-LIMIT      | 1          |
     * +---------------------+------------+
     */
    getAccounts(): Promise<GetAccountsResp>;
}

export class VIPLendingAPIImpl implements VIPLendingAPI {
    constructor(private transport: Transport) {}

    getAccountDetail(): Promise<GetAccountDetailResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/otc-loan/loan',
            null,
            GetAccountDetailResp,
            false,
        );
    }

    getAccounts(): Promise<GetAccountsResp> {
        return this.transport.call(
            'spot',
            false,
            'GET',
            '/api/v1/otc-loan/accounts',
            null,
            GetAccountsResp,
            false,
        );
    }
}
