// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetAccountDetailOrders implements Serializable<GetAccountDetailOrders> {
    /**
     * Loan Orders ID
     */
    orderId?: string;
    /**
     * Principal to Be Repaid
     */
    principal?: string;
    /**
     * Interest to Be Repaid
     */
    interest?: string;
    /**
     * Loan Currency
     */
    currency?: string;
    fromJson(input: string): GetAccountDetailOrders {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetAccountDetailOrders, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetAccountDetailOrders {
        return plainToInstance(GetAccountDetailOrders, jsonObject);
    }
}
