// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class BatchCancelOrdersData implements Serializable {
    /**
     *
     */
    orderId: string;

    /**
     *
     */
    clientOid: string;

    /**
     *
     */
    code: string;

    /**
     *
     */
    msg: string;

    private constructor() {
        // @ts-ignore
        this.orderId = null;
        // @ts-ignore
        this.clientOid = null;
        // @ts-ignore
        this.code = null;
        // @ts-ignore
        this.msg = null;
    }
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): BatchCancelOrdersData {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): BatchCancelOrdersData {
        return plainToClassFromExist(new BatchCancelOrdersData(), jsonObject);
    }
}
