// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetOrderListReq implements Serializable {
    /**
     * active or done, done as default. Only list orders for a specific status
     */
    status?: GetOrderListReq.StatusEnum;

    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * buy or sell
     */
    side?: GetOrderListReq.SideEnum;

    /**
     * limit, market, limit_stop or market_stop
     */
    type?: GetOrderListReq.TypeEnum;

    /**
     * Start time (milisecond)
     */
    startAt?: number;

    /**
     * End time (milisecond)
     */
    endAt?: number;

    /**
     * Current request page, The default currentPage is 1
     */
    currentPage?: number;

    /**
     * pageSize, The default pageSize is 50, The maximum cannot exceed 1000
     */
    pageSize?: number;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetOrderListReq` class.
     * The builder pattern allows step-by-step construction of a `GetOrderListReq` object.
     */
    static builder(): GetOrderListReqBuilder {
        return new GetOrderListReqBuilder(new GetOrderListReq());
    }

    /**
     * Creates a new instance of the `GetOrderListReq` class with the given data.
     */
    static create(data: {
        /**
         * active or done, done as default. Only list orders for a specific status
         */
        status?: GetOrderListReq.StatusEnum;
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
        /**
         * buy or sell
         */
        side?: GetOrderListReq.SideEnum;
        /**
         * limit, market, limit_stop or market_stop
         */
        type?: GetOrderListReq.TypeEnum;
        /**
         * Start time (milisecond)
         */
        startAt?: number;
        /**
         * End time (milisecond)
         */
        endAt?: number;
        /**
         * Current request page, The default currentPage is 1
         */
        currentPage?: number;
        /**
         * pageSize, The default pageSize is 50, The maximum cannot exceed 1000
         */
        pageSize?: number;
    }): GetOrderListReq {
        let obj = new GetOrderListReq();
        obj.status = data.status;
        obj.symbol = data.symbol;
        obj.side = data.side;
        obj.type = data.type;
        obj.startAt = data.startAt;
        obj.endAt = data.endAt;
        obj.currentPage = data.currentPage;
        obj.pageSize = data.pageSize;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetOrderListReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetOrderListReq {
        return plainToClassFromExist(new GetOrderListReq(), jsonObject);
    }
}

export namespace GetOrderListReq {
    export enum StatusEnum {
        /**
         *
         */
        ACTIVE = <any>'active',
        /**
         *
         */
        DONE = <any>'done',
    }
    export enum SideEnum {
        /**
         *
         */
        BUY = <any>'buy',
        /**
         *
         */
        SELL = <any>'sell',
    }
    export enum TypeEnum {
        /**
         *
         */
        LIMIT = <any>'limit',
        /**
         *
         */
        MARKET = <any>'market',
    }
}

export class GetOrderListReqBuilder {
    constructor(readonly obj: GetOrderListReq) {
        this.obj = obj;
    }
    /**
     * active or done, done as default. Only list orders for a specific status
     */
    setStatus(value: GetOrderListReq.StatusEnum): GetOrderListReqBuilder {
        this.obj.status = value;
        return this;
    }

    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetOrderListReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * buy or sell
     */
    setSide(value: GetOrderListReq.SideEnum): GetOrderListReqBuilder {
        this.obj.side = value;
        return this;
    }

    /**
     * limit, market, limit_stop or market_stop
     */
    setType(value: GetOrderListReq.TypeEnum): GetOrderListReqBuilder {
        this.obj.type = value;
        return this;
    }

    /**
     * Start time (milisecond)
     */
    setStartAt(value: number): GetOrderListReqBuilder {
        this.obj.startAt = value;
        return this;
    }

    /**
     * End time (milisecond)
     */
    setEndAt(value: number): GetOrderListReqBuilder {
        this.obj.endAt = value;
        return this;
    }

    /**
     * Current request page, The default currentPage is 1
     */
    setCurrentPage(value: number): GetOrderListReqBuilder {
        this.obj.currentPage = value;
        return this;
    }

    /**
     * pageSize, The default pageSize is 50, The maximum cannot exceed 1000
     */
    setPageSize(value: number): GetOrderListReqBuilder {
        this.obj.pageSize = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetOrderListReq {
        return this.obj;
    }
}
