// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class BatchCancelOrdersClientOidsList implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol: string;

    /**
     *
     */
    clientOid: string;

    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.clientOid = null;
    }
    /**
     * Creates a new instance of the `BatchCancelOrdersClientOidsList` class.
     * The builder pattern allows step-by-step construction of a `BatchCancelOrdersClientOidsList` object.
     */
    static builder(): BatchCancelOrdersClientOidsListBuilder {
        return new BatchCancelOrdersClientOidsListBuilder(new BatchCancelOrdersClientOidsList());
    }

    /**
     * Creates a new instance of the `BatchCancelOrdersClientOidsList` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol: string;
        /**
         *
         */
        clientOid: string;
    }): BatchCancelOrdersClientOidsList {
        let obj = new BatchCancelOrdersClientOidsList();
        obj.symbol = data.symbol;
        obj.clientOid = data.clientOid;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): BatchCancelOrdersClientOidsList {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): BatchCancelOrdersClientOidsList {
        return plainToClassFromExist(new BatchCancelOrdersClientOidsList(), jsonObject);
    }
}

export class BatchCancelOrdersClientOidsListBuilder {
    constructor(readonly obj: BatchCancelOrdersClientOidsList) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): BatchCancelOrdersClientOidsListBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     *
     */
    setClientOid(value: string): BatchCancelOrdersClientOidsListBuilder {
        this.obj.clientOid = value;
        return this;
    }

    build(): BatchCancelOrdersClientOidsList {
        return this.obj;
    }
}
