// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class BatchCancelOrdersClientOidsList
    implements Serializable<BatchCancelOrdersClientOidsList>
{
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;
    /**
     *
     */
    clientOid?: string;

    /**
     * Creates a new instance of the `BatchCancelOrdersClientOidsList` class.
     * The builder pattern allows step-by-step construction of a `BatchCancelOrdersClientOidsList` object.
     */
    static builder(): BatchCancelOrdersClientOidsListBuilder {
        return new BatchCancelOrdersClientOidsListBuilder();
    }

    /**
     * Creates a new instance of the `BatchCancelOrdersClientOidsList` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
        /**
         *
         */
        clientOid?: string;
    }): BatchCancelOrdersClientOidsList {
        let obj = new BatchCancelOrdersClientOidsList();
        obj.symbol = data.symbol;
        obj.clientOid = data.clientOid;
        return obj;
    }

    fromJson(input: string): BatchCancelOrdersClientOidsList {
        const jsonObject = JSON.parse(input);
        return plainToInstance(BatchCancelOrdersClientOidsList, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): BatchCancelOrdersClientOidsList {
        return plainToInstance(BatchCancelOrdersClientOidsList, jsonObject);
    }
}

export class BatchCancelOrdersClientOidsListBuilder {
    obj: BatchCancelOrdersClientOidsList = new BatchCancelOrdersClientOidsList();
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): BatchCancelOrdersClientOidsListBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     *
     */
    setClientOid(value: string): BatchCancelOrdersClientOidsListBuilder {
        this.obj.clientOid = value;
        return this;
    }

    build(): BatchCancelOrdersClientOidsList {
        return this.obj;
    }
}
