// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetRecentClosedOrdersReq implements Serializable<GetRecentClosedOrdersReq> {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * Creates a new instance of the `GetRecentClosedOrdersReq` class.
     * The builder pattern allows step-by-step construction of a `GetRecentClosedOrdersReq` object.
     */
    static builder(): GetRecentClosedOrdersReqBuilder {
        return new GetRecentClosedOrdersReqBuilder();
    }

    /**
     * Creates a new instance of the `GetRecentClosedOrdersReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
    }): GetRecentClosedOrdersReq {
        let obj = new GetRecentClosedOrdersReq();
        obj.symbol = data.symbol;
        return obj;
    }

    fromJson(input: string): GetRecentClosedOrdersReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetRecentClosedOrdersReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetRecentClosedOrdersReq {
        return plainToInstance(GetRecentClosedOrdersReq, jsonObject);
    }
}

export class GetRecentClosedOrdersReqBuilder {
    obj: GetRecentClosedOrdersReq = new GetRecentClosedOrdersReq();
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetRecentClosedOrdersReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): GetRecentClosedOrdersReq {
        return this.obj;
    }
}
