// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetOpenOrderValueResp implements Response<RestResponse> {
    /**
     * Total number of the unexecuted buy orders
     */
    openOrderBuySize: number;

    /**
     * Total number of the unexecuted sell orders
     */
    openOrderSellSize: number;

    /**
     * Value of all the unexecuted buy orders
     */
    openOrderBuyCost: string;

    /**
     * Value of all the unexecuted sell orders
     */
    openOrderSellCost: string;

    /**
     * settlement currency
     */
    settleCurrency: string;

    private constructor() {
        // @ts-ignore
        this.openOrderBuySize = null;
        // @ts-ignore
        this.openOrderSellSize = null;
        // @ts-ignore
        this.openOrderBuyCost = null;
        // @ts-ignore
        this.openOrderSellCost = null;
        // @ts-ignore
        this.settleCurrency = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetOpenOrderValueResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetOpenOrderValueResp {
        return plainToClassFromExist(new GetOpenOrderValueResp(), jsonObject);
    }
}
