// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class CancelOrderByClientOidReq implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * client order id
     */
    @Reflect.metadata('path', 'clientOid')
    clientOid?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `CancelOrderByClientOidReq` class.
     * The builder pattern allows step-by-step construction of a `CancelOrderByClientOidReq` object.
     */
    static builder(): CancelOrderByClientOidReqBuilder {
        return new CancelOrderByClientOidReqBuilder(new CancelOrderByClientOidReq());
    }

    /**
     * Creates a new instance of the `CancelOrderByClientOidReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
        /**
         * client order id
         */
        clientOid?: string;
    }): CancelOrderByClientOidReq {
        let obj = new CancelOrderByClientOidReq();
        obj.symbol = data.symbol;
        obj.clientOid = data.clientOid;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): CancelOrderByClientOidReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): CancelOrderByClientOidReq {
        return plainToClassFromExist(new CancelOrderByClientOidReq(), jsonObject);
    }
}

export class CancelOrderByClientOidReqBuilder {
    constructor(readonly obj: CancelOrderByClientOidReq) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): CancelOrderByClientOidReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * client order id
     */
    setClientOid(value: string): CancelOrderByClientOidReqBuilder {
        this.obj.clientOid = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): CancelOrderByClientOidReq {
        return this.obj;
    }
}
