// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetOrderByClientOidResp implements Response<GetOrderByClientOidResp, RestResponse> {
    /**
     * Order ID
     */
    id?: string;
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;
    /**
     * Order type, market order or limit order
     */
    type?: GetOrderByClientOidResp.TypeEnum;
    /**
     * Transaction side
     */
    side?: GetOrderByClientOidResp.SideEnum;
    /**
     * Order price
     */
    price?: string;
    /**
     * Order quantity
     */
    size?: number;
    /**
     * Order value
     */
    value?: string;
    /**
     * Executed size of funds
     */
    dealValue?: string;
    /**
     * Executed quantity
     */
    dealSize?: number;
    /**
     * [Self Trade Prevention](https://www.kucoin.com/docs-new/doc-338146) is divided into these strategies: CN, CO, CB. Not supported DC at the moment.
     */
    stp?: GetOrderByClientOidResp.StpEnum;
    /**
     * Stop order type (stop limit or stop market)
     */
    stop?: string;
    /**
     * Trigger price type of stop orders
     */
    stopPriceType?: GetOrderByClientOidResp.StopPriceTypeEnum;
    /**
     * Mark to show whether the stop order is triggered
     */
    stopTriggered?: boolean;
    /**
     * Trigger price of stop orders
     */
    stopPrice?: number;
    /**
     * Time in force policy type
     */
    timeInForce?: string;
    /**
     * Mark of post only
     */
    postOnly?: boolean;
    /**
     * Mark of the hidden order
     */
    hidden?: boolean;
    /**
     * Mark of the iceberg order
     */
    iceberg?: boolean;
    /**
     * Leverage of the order
     */
    leverage?: string;
    /**
     * A mark to forcely hold the funds for an order
     */
    forceHold?: boolean;
    /**
     * A mark to close the position
     */
    closeOrder?: boolean;
    /**
     * Visible size of the iceberg order
     */
    visibleSize?: number;
    /**
     * Unique order id created by users to identify their orders
     */
    clientOid?: string;
    /**
     * Remark
     */
    remark?: string;
    /**
     * tag order source
     */
    tags?: string;
    /**
     * Mark of the active orders
     */
    isActive?: boolean;
    /**
     * Mark of the canceled orders
     */
    cancelExist?: boolean;
    /**
     * Time the order created
     */
    createdAt?: number;
    /**
     * last update time
     */
    updatedAt?: number;
    /**
     * Order Endtime
     */
    endAt?: number;
    /**
     * Order create time in nanosecond
     */
    orderTime?: number;
    /**
     * settlement currency
     */
    settleCurrency?: string;
    /**
     * Margin mode: ISOLATED (isolated), CROSS (cross margin).
     */
    marginMode?: GetOrderByClientOidResp.MarginModeEnum;
    /**
     * Average transaction price, forward contract average transaction price = sum (transaction value) / sum (transaction quantity), reverse contract average transaction price = sum (transaction quantity) / sum (transaction value). Transaction quantity = lots * multiplier
     */
    avgDealPrice?: string;
    /**
     * Value of the executed orders
     */
    filledSize?: number;
    /**
     * Executed order quantity
     */
    filledValue?: string;
    /**
     * order status: “open” or “done”
     */
    status?: GetOrderByClientOidResp.StatusEnum;
    /**
     * A mark to reduce the position size only
     */
    reduceOnly?: boolean;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetOrderByClientOidResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetOrderByClientOidResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetOrderByClientOidResp {
        return plainToInstance(GetOrderByClientOidResp, jsonObject);
    }
}

export namespace GetOrderByClientOidResp {
    export enum TypeEnum {
        /**
         * Market Order
         */
        MARKET = <any>'market',
        /**
         * Limit Order
         */
        LIMIT = <any>'limit',
    }
    export enum SideEnum {
        /**
         * buy
         */
        BUY = <any>'buy',
        /**
         * sell
         */
        SELL = <any>'sell',
    }
    export enum StpEnum {
        /**
         * None
         */
        NULL = <any>'',
        /**
         * Cancel new, Cancel the new order
         */
        CN = <any>'CN',
        /**
         * Cancel old, Cancel the old order
         */
        CO = <any>'CO',
        /**
         * Cancel both, Cancel both sides
         */
        CB = <any>'CB',
    }
    export enum StopPriceTypeEnum {
        /**
         * None
         */
        NULL = <any>'',
        /**
         * TP for trade price, The last trade price is the last price at which an order was filled. This price can be found in the latest match message.
         */
        TRADE_PRICE = <any>'TP',
        /**
         * MP for mark price, The mark price can be obtained through relevant OPEN API for index services
         */
        MARK_PRICE = <any>'MP',
        /**
         * IP for index price, The index price can be obtained through relevant OPEN API for index services
         */
        INDEX_PRICE = <any>'IP',
    }
    export enum MarginModeEnum {
        /**
         * Cross margin
         */
        CROSS = <any>'CROSS',
        /**
         * Isolated margin
         */
        ISOLATED = <any>'ISOLATED',
    }
    export enum StatusEnum {
        /**
         * open order
         */
        OPEN = <any>'open',
        /**
         * done order
         */
        DONE = <any>'done',
    }
}
