// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetMarkPriceListData } from './model_get_mark_price_list_data';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetMarkPriceListResp implements Response<GetMarkPriceListResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetMarkPriceListData)
    data?: Array<GetMarkPriceListData>;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetMarkPriceListResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetMarkPriceListResp, { data: jsonObject });
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }

    fromObject(jsonObject: Object): GetMarkPriceListResp {
        return plainToInstance(GetMarkPriceListResp, { data: jsonObject });
    }
}
