// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetETFInfoData implements Serializable<GetETFInfoData> {
    /**
     * ETF Currency
     */
    currency?: string;
    /**
     * Net worth
     */
    netAsset?: string;
    /**
     * Target leverage
     */
    targetLeverage?: string;
    /**
     * Actual leverage
     */
    actualLeverage?: string;
    /**
     * The amount of currency issued
     */
    issuedSize?: string;
    /**
     * Basket information
     */
    basket?: string;
    fromJson(input: string): GetETFInfoData {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetETFInfoData, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetETFInfoData {
        return plainToInstance(GetETFInfoData, jsonObject);
    }
}
