// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetIsolatedMarginSymbolsData } from './model_get_isolated_margin_symbols_data';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetIsolatedMarginSymbolsResp
    implements Response<GetIsolatedMarginSymbolsResp, RestResponse>
{
    /**
     *
     */
    @Type(() => GetIsolatedMarginSymbolsData)
    data?: Array<GetIsolatedMarginSymbolsData>;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetIsolatedMarginSymbolsResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetIsolatedMarginSymbolsResp, { data: jsonObject });
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }

    fromObject(jsonObject: Object): GetIsolatedMarginSymbolsResp {
        return plainToInstance(GetIsolatedMarginSymbolsResp, { data: jsonObject });
    }
}
