// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import 'reflect-metadata';
import { Serializable } from '@internal/interfaces/serializable';

export class GetMarkPriceDetailReq implements Serializable {
    /**
     * symbol
     */
    @Reflect.metadata('path', 'symbol')
    symbol?: string;

    private constructor() {}
    /**
     * Creates a new instance of the `GetMarkPriceDetailReq` class.
     * The builder pattern allows step-by-step construction of a `GetMarkPriceDetailReq` object.
     */
    static builder(): GetMarkPriceDetailReqBuilder {
        return new GetMarkPriceDetailReqBuilder(new GetMarkPriceDetailReq());
    }

    /**
     * Creates a new instance of the `GetMarkPriceDetailReq` class with the given data.
     */
    static create(data: {
        /**
         * symbol
         */
        symbol?: string;
    }): GetMarkPriceDetailReq {
        let obj = new GetMarkPriceDetailReq();
        obj.symbol = data.symbol;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetMarkPriceDetailReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetMarkPriceDetailReq {
        return plainToClassFromExist(new GetMarkPriceDetailReq(), jsonObject);
    }
}

export class GetMarkPriceDetailReqBuilder {
    constructor(readonly obj: GetMarkPriceDetailReq) {
        this.obj = obj;
    }
    /**
     * symbol
     */
    setSymbol(value: string): GetMarkPriceDetailReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): GetMarkPriceDetailReq {
        return this.obj;
    }
}
