// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { OrderbookIncrementChanges } from './model_orderbook_increment_changes';
import { WsMessage } from '@model/common';
import { WebSocketMessageCallback } from '@internal/interfaces/websocket';
import { Response } from '@internal/interfaces/response';

export class OrderbookIncrementEvent implements Response<OrderbookIncrementEvent, WsMessage> {
    /**
     *
     */
    changes?: OrderbookIncrementChanges;
    /**
     *
     */
    sequenceEnd?: number;
    /**
     *
     */
    sequenceStart?: number;
    /**
     *
     */
    symbol?: string;
    /**
     * milliseconds
     */
    time?: number;
    /**
     * common response
     */
    @Exclude()
    private commonResponse?: WsMessage;

    setCommonResponse(response: WsMessage): void {
        this.commonResponse = response;
    }

    fromJson(input: string): OrderbookIncrementEvent {
        const jsonObject = JSON.parse(input);
        return plainToInstance(OrderbookIncrementEvent, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): OrderbookIncrementEvent {
        return plainToInstance(OrderbookIncrementEvent, jsonObject);
    }
}

export type OrderbookIncrementEventCallback = (
    topic: string,
    subject: string,
    data: OrderbookIncrementEvent,
) => void;

export class OrderbookIncrementEventCallbackWrapper implements WebSocketMessageCallback {
    callback: OrderbookIncrementEventCallback;

    constructor(callback: OrderbookIncrementEventCallback) {
        this.callback = callback;
    }

    onMessage(msg: WsMessage): void {
        let event = new OrderbookIncrementEvent().fromObject(msg.rawData);
        event.setCommonResponse(msg);
        this.callback(msg.topic, msg.subject, event);
    }
}
