// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { OrderbookIncrementChanges } from './model_orderbook_increment_changes';
import { WsMessage } from '@model/common';
import { WebSocketMessageCallback } from '@internal/interfaces/websocket';
import { Response } from '@internal/interfaces/serializable';

export class OrderbookIncrementEvent implements Response<WsMessage> {
    /**
     *
     */
    changes: OrderbookIncrementChanges;
    /**
     *
     */
    sequenceEnd: number;
    /**
     *
     */
    sequenceStart: number;
    /**
     *
     */
    symbol: string;
    /**
     * milliseconds
     */
    time: number;

    private constructor() {
        // @ts-ignore
        this.changes = null;
        // @ts-ignore
        this.sequenceEnd = null;
        // @ts-ignore
        this.sequenceStart = null;
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.time = null;
    }
    /**
     * common response
     */
    @Exclude()
    private commonResponse?: WsMessage;

    setCommonResponse(response: WsMessage): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): OrderbookIncrementEvent {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): OrderbookIncrementEvent {
        return plainToClassFromExist(new OrderbookIncrementEvent(), jsonObject);
    }
}

export type OrderbookIncrementEventCallback = (
    topic: string,
    subject: string,
    data: OrderbookIncrementEvent,
) => void;

export class OrderbookIncrementEventCallbackWrapper implements WebSocketMessageCallback {
    constructor(private callback: OrderbookIncrementEventCallback) {
        this.callback = callback;
    }

    onMessage(msg: WsMessage): void {
        let event = OrderbookIncrementEvent.fromObject(msg.data);
        event.setCommonResponse(msg);
        this.callback(msg.topic, msg.subject, event);
    }
}
