// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class OrderbookLevel50Changes implements Serializable<OrderbookLevel50Changes> {
    /**
     *
     */
    asks?: Array<Array<string>>;
    /**
     *
     */
    bids?: Array<Array<string>>;

    fromJson(input: string): OrderbookLevel50Changes {
        const jsonObject = JSON.parse(input);
        return plainToInstance(OrderbookLevel50Changes, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): OrderbookLevel50Changes {
        return plainToInstance(OrderbookLevel50Changes, jsonObject);
    }
}
