// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class SymbolSnapshotDataMarketChange1h implements Serializable {
    /**
     *
     */
    changePrice?: number;
    /**
     *
     */
    changeRate?: number;
    /**
     *
     */
    high?: number;
    /**
     *
     */
    low?: number;
    /**
     *
     */
    open?: number;
    /**
     *
     */
    vol?: number;
    /**
     *
     */
    volValue?: number;

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): SymbolSnapshotDataMarketChange1h {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): SymbolSnapshotDataMarketChange1h {
        return plainToClassFromExist(new SymbolSnapshotDataMarketChange1h(), jsonObject);
    }
}
