// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { Type, instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { GetSpotActualFeeData } from './model_get_spot_actual_fee_data';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';

export class GetSpotActualFeeResp implements Response<GetSpotActualFeeResp, RestResponse> {
    /**
     *
     */
    @Type(() => GetSpotActualFeeData)
    data?: Array<GetSpotActualFeeData>;

    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetSpotActualFeeResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetSpotActualFeeResp, { data: jsonObject });
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this.data));
    }

    fromObject(jsonObject: Object): GetSpotActualFeeResp {
        return plainToInstance(GetSpotActualFeeResp, { data: jsonObject });
    }
}
