// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToInstance } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/response';
export class GetFuturesActualFeeResp implements Response<GetFuturesActualFeeResp, RestResponse> {
    /**
     * The unique identity of the trading pair and will not change even if the trading pair is renamed
     */
    symbol?: string;
    /**
     * Actual taker fee rate of the trading pair
     */
    takerFeeRate?: string;
    /**
     * Actual maker fee rate of the trading pair
     */
    makerFeeRate?: string;
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    fromJson(input: string): GetFuturesActualFeeResp {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetFuturesActualFeeResp, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetFuturesActualFeeResp {
        return plainToInstance(GetFuturesActualFeeResp, jsonObject);
    }
}
