// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetSpotActualFeeData implements Serializable<GetSpotActualFeeData> {
    /**
     * The unique identity of the trading pair and will not change even if the trading pair is renamed
     */
    symbol?: string;
    /**
     * Actual taker fee rate of the symbol
     */
    takerFeeRate?: string;
    /**
     * Actual maker fee rate of the symbol
     */
    makerFeeRate?: string;
    fromJson(input: string): GetSpotActualFeeData {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetSpotActualFeeData, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetSpotActualFeeData {
        return plainToInstance(GetSpotActualFeeData, jsonObject);
    }
}
