// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { GetAccountMargins } from './model_get_account_margins';
import { Type, instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { GetAccountLtv } from './model_get_account_ltv';
import { GetAccountOrders } from './model_get_account_orders';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class GetAccountResp implements Response<RestResponse> {
    /**
     * Master account UID
     */
    parentUid: string;

    /**
     * Loan Orders
     */
    @Type(() => GetAccountOrders)
    orders: Array<GetAccountOrders>;

    /**
     *
     */
    @Type(() => GetAccountLtv)
    ltv: GetAccountLtv;

    /**
     * Total Margin Amount (USDT)
     */
    totalMarginAmount: string;

    /**
     * Total Maintenance Margin for Restricted Transfers (USDT)
     */
    transferMarginAmount: string;

    /**
     * Margins
     */
    @Type(() => GetAccountMargins)
    margins: Array<GetAccountMargins>;

    private constructor() {
        // @ts-ignore
        this.parentUid = null;
        // @ts-ignore
        this.orders = null;
        // @ts-ignore
        this.ltv = null;
        // @ts-ignore
        this.totalMarginAmount = null;
        // @ts-ignore
        this.transferMarginAmount = null;
        // @ts-ignore
        this.margins = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): GetAccountResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): GetAccountResp {
        return plainToClassFromExist(new GetAccountResp(), jsonObject);
    }
}
