// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class GetCrossMarginLeverageReq implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * Private constructor, please use the corresponding static methods to construct the object.
     */
    private constructor() {}
    /**
     * Creates a new instance of the `GetCrossMarginLeverageReq` class.
     * The builder pattern allows step-by-step construction of a `GetCrossMarginLeverageReq` object.
     */
    static builder(): GetCrossMarginLeverageReqBuilder {
        return new GetCrossMarginLeverageReqBuilder(new GetCrossMarginLeverageReq());
    }

    /**
     * Creates a new instance of the `GetCrossMarginLeverageReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
    }): GetCrossMarginLeverageReq {
        let obj = new GetCrossMarginLeverageReq();
        obj.symbol = data.symbol;
        return obj;
    }

    /**
     * Convert the object to a JSON string.
     */
    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }
    /**
     * Create an object from a JSON string.
     */
    static fromJson(input: string): GetCrossMarginLeverageReq {
        return this.fromObject(JSON.parse(input));
    }
    /**
     * Create an object from Js Object.
     */
    static fromObject(jsonObject: Object): GetCrossMarginLeverageReq {
        return plainToClassFromExist(new GetCrossMarginLeverageReq(), jsonObject);
    }
}

export class GetCrossMarginLeverageReqBuilder {
    constructor(readonly obj: GetCrossMarginLeverageReq) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetCrossMarginLeverageReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * Get the final object.
     */
    build(): GetCrossMarginLeverageReq {
        return this.obj;
    }
}
