// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, Exclude, plainToClassFromExist } from 'class-transformer';
import { RestResponse } from '@model/common';
import { Response } from '@internal/interfaces/serializable';

export class ModifyMarginLeverageResp implements Response<RestResponse> {
    /**
     *
     */
    symbol: string;

    /**
     *
     */
    leverage: string;

    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.leverage = null;
    }
    /**
     * common response
     */
    @Exclude()
    commonResponse?: RestResponse;

    setCommonResponse(response: RestResponse): void {
        this.commonResponse = response;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): ModifyMarginLeverageResp {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): ModifyMarginLeverageResp {
        return plainToClassFromExist(new ModifyMarginLeverageResp(), jsonObject);
    }
}
