// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToClassFromExist } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';

export class RemoveIsolatedMarginReq implements Serializable {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol: string;

    /**
     * The size of the position that can be deposited. If it is USDT-margin, it represents the amount of USDT. If it is coin-margin, this value represents the number of coins
     */
    withdrawAmount: string;

    private constructor() {
        // @ts-ignore
        this.symbol = null;
        // @ts-ignore
        this.withdrawAmount = null;
    }
    /**
     * Creates a new instance of the `RemoveIsolatedMarginReq` class.
     * The builder pattern allows step-by-step construction of a `RemoveIsolatedMarginReq` object.
     */
    static builder(): RemoveIsolatedMarginReqBuilder {
        return new RemoveIsolatedMarginReqBuilder(new RemoveIsolatedMarginReq());
    }

    /**
     * Creates a new instance of the `RemoveIsolatedMarginReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol: string;
        /**
         * The size of the position that can be deposited. If it is USDT-margin, it represents the amount of USDT. If it is coin-margin, this value represents the number of coins
         */
        withdrawAmount: string;
    }): RemoveIsolatedMarginReq {
        let obj = new RemoveIsolatedMarginReq();
        obj.symbol = data.symbol;
        obj.withdrawAmount = data.withdrawAmount;
        return obj;
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    static fromJson(input: string): RemoveIsolatedMarginReq {
        return this.fromObject(JSON.parse(input));
    }

    static fromObject(jsonObject: Object): RemoveIsolatedMarginReq {
        return plainToClassFromExist(new RemoveIsolatedMarginReq(), jsonObject);
    }
}

export class RemoveIsolatedMarginReqBuilder {
    constructor(readonly obj: RemoveIsolatedMarginReq) {
        this.obj = obj;
    }
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): RemoveIsolatedMarginReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    /**
     * The size of the position that can be deposited. If it is USDT-margin, it represents the amount of USDT. If it is coin-margin, this value represents the number of coins
     */
    setWithdrawAmount(value: string): RemoveIsolatedMarginReqBuilder {
        this.obj.withdrawAmount = value;
        return this;
    }

    build(): RemoveIsolatedMarginReq {
        return this.obj;
    }
}
