// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

import { instanceToPlain, plainToInstance } from 'class-transformer';
import { Serializable } from '@internal/interfaces/serializable';
export class GetMaxWithdrawMarginReq implements Serializable<GetMaxWithdrawMarginReq> {
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    symbol?: string;

    /**
     * Creates a new instance of the `GetMaxWithdrawMarginReq` class.
     * The builder pattern allows step-by-step construction of a `GetMaxWithdrawMarginReq` object.
     */
    static builder(): GetMaxWithdrawMarginReqBuilder {
        return new GetMaxWithdrawMarginReqBuilder();
    }

    /**
     * Creates a new instance of the `GetMaxWithdrawMarginReq` class with the given data.
     */
    static create(data: {
        /**
         * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
         */
        symbol?: string;
    }): GetMaxWithdrawMarginReq {
        let obj = new GetMaxWithdrawMarginReq();
        obj.symbol = data.symbol;
        return obj;
    }

    fromJson(input: string): GetMaxWithdrawMarginReq {
        const jsonObject = JSON.parse(input);
        return plainToInstance(GetMaxWithdrawMarginReq, jsonObject);
    }

    toJson(): string {
        return JSON.stringify(instanceToPlain(this));
    }

    fromObject(jsonObject: Object): GetMaxWithdrawMarginReq {
        return plainToInstance(GetMaxWithdrawMarginReq, jsonObject);
    }
}

export class GetMaxWithdrawMarginReqBuilder {
    obj: GetMaxWithdrawMarginReq = new GetMaxWithdrawMarginReq();
    /**
     * Symbol of the contract, Please refer to [Get Symbol endpoint: symbol](https://www.kucoin.com/docs-new/api-3470220)
     */
    setSymbol(value: string): GetMaxWithdrawMarginReqBuilder {
        this.obj.symbol = value;
        return this;
    }

    build(): GetMaxWithdrawMarginReq {
        return this.obj;
    }
}
